#!/bin/bash 
#set -x

if [ "$1" != "" ]; then
    mkdir ./"$1"
    mkdir ./"$1"/well_data
    mkdir ./"$1"/production_data
else
    mkdir ./well_data
    mkdir ./production_data    
fi

source /prog/res/komodo/testing-py3/enable

python -m venv venv
source ./venv/bin/activate

pip install --upgrade pip
pip install libecl 
pip install webviz-config
pip install webviz-subsurface
pip install webviz-config-equinor
pip install ruamel.yaml
pip install requests
pip install .

echo "Installation completed"




