#!/bin/bash 
#set -x

if [ "$1" != "" ]; then
    mkdir webviz_4d/"$1"
    mkdir webviz_4d/"$1"/well_data
    mkdir webviz_4d/"$1"/production_data
else
    mkdir webviz_4d/well_data
    mkdir webviz_4d/production_data    
fi

source /prog/res/komodo/testing-py3/enable

if [ -d reper ]; then
    echo "ERROR: reper directory already exist, installation aborted"
    echo "Type rm -rf reper to remove the directory"
    exit
fi

git clone git@github.com:equinor/reper.git

python -m venv venv
source venv/bin/activate

pip install --upgrade pip
pip install libecl 
pip install webviz-config
pip install webviz-subsurface
pip install webviz-config-equinor
pip install ruamel.yaml
pip install requests
pip install ./reper
pip install ./webviz-4d

echo "Installation completed"




