#!/bin/bash 
#set -x

if [ "$#" -ne 1 ]; then
    echo "Field name is missing, must be given as one string"
    echo "Execution stopped"
    exit
fi

unset PYTHONPATH
source ./venv/bin/activate

rm -f update_webviz-4d.txt

echo "Extract wellbores from REP ..."
python data_preparation/extract_wellbores_from_rep.py Grane
echo ""

echo "Compile well metadata"
python data_preparation/compile_well_metadata.py configurations/config_template.yaml > update_webviz-4d.txt
echo ""

echo "Compile production data"
python data_preparation/compile_production_data.py configurations/config_template.yaml >> update_webviz-4d.txt
echo ""

echo "Create production tables" 
python data_preparation/create_production_tables.py configurations/config_template.yaml >> update_webviz-4d.txt
echo ""

echo "Create well lists"
python data_preparation/create_well_lists.py configurations/config_template.yaml >> update_webviz-4d.txt
echo ""

echo "Check well lists"
python data_preparation/check_well_lists.py configurations/config_template.yaml >> update_webviz-4d.txt
echo ""

echo "Log file created: update_webviz-4d.txt"
