title: WebViz-4D Johan Sverdrup

shared_settings:
    fmu_directory: /scratch/johan_sverdrup2/eza/2020a_b007_0_0_08052020
    simulated_maps:       
        realization_names: [realization-*]
        ensemble_names: [pred]
        map_directories: [share/results/maps] 
    
pages:  
  - title: Front page
    content:  
      - Markdown:
          markdown_file: ./front_page.md
          
  - title: Simulated maps
    content:
      - SurfaceViewer4D:
          wellfolder: ../johan_sverdrup/well_data              
          production_data: ../johan_sverdrup/production_data    
          
          well_suffix: .w      
          map_suffix: .gri
          surface_metadata: surface_metadata.csv
          
          default_interval: 2020-01-01-2019-01-01
                                     
          settings:  ./js_eli_settings.yaml  
          
  - title: One simulated map
    content:
      - SurfaceViewer4D1:
          wellfolder: ../johan_sverdrup/well_data              
          production_data: ../johan_sverdrup/production_data    
          
          well_suffix: .w      
          map_suffix: .gri
          surface_metadata: surface_metadata.csv  
          
          default_interval: 2020-01-01-2019-01-01 
          
          settings:  ./js_eli_settings.yaml         
            
  - title: Well overview 
    content:
      - DataTable:
          csv_file: ../johan_sverdrup/well_data/wellbore_overview.csv
          sorting: True
          filtering: True                  
          
  - title: Production plots  
    content:
        - TablePlotter:
            csv_file: ../johan_sverdrup/production_data/production_fluid_table.csv
            plot_options:
              x: 4D_interval
              y: Volumes
              type: bar   
              color: Fluid
              barmode: group
            filter_cols:
              - Well_name  
              - 4D_interval
              - Fluid  
            filter_defaults: 
              Well_name: [NO16/2-D-6]  
            column_color_discrete_maps:
              Fluid:
                 Oil_[Sm3]: '#00ff00'
                 Gas_[kSm3]: '#ff0000'
                 Water_[Sm3]: '#0000ff'  
    
  - title: Injection plots  
    content:
        - TablePlotter:
            csv_file: ../johan_sverdrup/production_data/injection_fluid_table.csv
            plot_options:
              x: 4D_interval
              y: Volumes
              type: bar   
              color: Fluid
              barmode: group
            filter_cols:
              - Well_name  
              - 4D_interval
              - Fluid  
            filter_defaults: 
              Well_name: [NO16/2-D-9]  
            column_color_discrete_maps:
              Fluid:
                 Injected_Gas_[kSm3]: '#fa0000'
                 Injected_Water_[Sm3]: '#0000fa'                                              
          
  - title: Oil production volumes 
    content:
      - DataTable:
          csv_file: ../johan_sverdrup/production_data/BORE_OIL_VOL.csv  
          sorting: True
          filtering: True   
          
  - title: Gas production volumes 
    content:
      - DataTable:
          csv_file: ../johan_sverdrup/production_data/BORE_GAS_VOL.csv  
          sorting: True
          filtering: True       
          
  - title: Water production volumes 
    content:
      - DataTable:
          csv_file: ../johan_sverdrup/production_data/BORE_WAT_VOL.csv  
          sorting: True
          filtering: True             
          
  - title: Gas injection volumes 
    content:
      - DataTable:
          csv_file: ../johan_sverdrup/production_data/BORE_GI_VOL.csv  
          sorting: True
          filtering: True     
          
  - title: Water injection volumes  
    content:
      - DataTable:
          csv_file: ../johan_sverdrup/production_data/BORE_WI_VOL.csv  
          sorting: True
          filtering: True           
                     
  - title: Documentation
    content:  
      - Markdown:
          markdown_file: ./documentation.md
      - SyntaxHighlighter:
          filename: ./js_config.yaml
          dark_theme: yes   
      - SyntaxHighlighter:
          filename: ./js_eli_settings.yaml
          dark_theme: yes             
           

