depth_maps:
    top_reservoir: /private/ashska/development/grane/maps/toplowerheimdal--depthsurface.gri
map_settings:
    colormaps_folder: /private/ashska/development/webviz-4d/colormaps/
    colormaps_settings: /private/ashska/development/webviz-4d_fork/webviz-4d/configurations/js_attribute_maps_v2.csv
    default_colormap: viridis
    attribute_settings:     
        4d_max:
            color:   dsg_spectrum
            min:    0.0
            max:    0.02
        4d_rms:
            color:   dsg_spectrum
            min:  0
            max:  0.02
        4d_min:
            color:   dsg_spectrum_r  
            min:   -0.02
            max:   0    
        4d_mean:
            color:   dsg_spectrum  
            min:   0
            max:   0.02     
        timeshift:
            color:   seismic 
            min: -2.0
            max:  2.0    
        
well_colors:
    default: black
    oil_open: lime
    oil_production: green
    gas_open: salmon
    gas_production: red
    gas_injection:  magenta
    water_injection: blue
    wag_injection: pink   
    planned: purple     
        
date_labels:
    20140915: PRM0
    20150515: PRM1
    20150915: PRM2
    20160515: PRM3
    20160915: PRM4    
    20170515: PRM5
    20170915: PRM6
    20180515: PRM7
    20180915: PRM8
    20190515: PRM9
    20190915: PRM10
    

    
  
     
    
