depth_maps:
    top_reservoir: /scratch/johan_sverdrup2/eza/2020a_b007_0_0_08052020/realization-0/pred/share/results/maps/aasgard_fm_top--depthsurface_final.gri
map_settings:
    colormaps_folder: /private/ashska/development/webviz-4d/colormaps/
    default_colormap: viridis
    attribute_settings:     
        4d_max:
            color:   geoprobe
            min:    -0.02
            max:    0.02
        4d_rms:
            color:   dsg_spectrum
            min:  0
            max:  0.02
        4d_min:
            color:   geoprobe
            min:   -0.02
            max:   0    
        4d_mean:
            color:   geoprobe  
            min:   
            max:   0.02     
        timeshift:
            color:   geoprobe 
            min: -2.0
            max:  2.0    
        
well_colors:
    default: black
    oil_open: lime
    oil_production: green
    gas_open: salmon
    gas_production: red
    gas_injection:  magenta
    water_injection: blue
    wag_injection: pink   
    planned: purple     
        
date_labels:
    20140915: PRM0
    20150515: PRM1
    20150915: PRM2
    20160515: PRM3
    20160915: PRM4    
    20170515: PRM5
    20170915: PRM6
    20180515: PRM7
    20180915: PRM8
    20190515: PRM9
    20190915: PRM10
    

    
  
     
    
