title: WebViz-4D Johan Sverdrup

shared_settings:
    fmu_directory: /scratch/johan_sverdrup2/2020a_r008p0p0_ref/2020a_r008p0p0_ref
    simulated_maps:       
        realization_names: [realization-*]
        ensemble_names: [pred]
        map_directories: [share/maps/recoverables]  
    
pages:  
  - title: Front page
    content:  
      - Markdown:
          markdown_file: ./front_page.md
          
  - title: Simulated maps
    content:
      - SurfaceViewer4D:
          wellfolder: ../johan_sverdrup/well_data              
          production_data: ../johan_sverdrup/production_data    
          
          well_suffix: .w      
          map_suffix: .gri
          surface_metadata: surface_metadata.csv
                                     
          settings:  ./settings_template.yaml
          
  - title: One observed map
    content:
      - SurfaceViewer4D1:
          wellfolder: ../grane/well_data              
          production_data: ../grane/production_data    
          
          well_suffix: .w      
          map_suffix: .gri
          surface_metadata: surface_metadata_v2.csv
                          
          map1_defaults:
            attribute: maxpos
            name: all
            map_type: observations
            ensemble: iter-0
            realization: realization-0 
            
          default_interval: 2019-09-15-2019-05-15    
          
          settings:  ./js_eli_settings.yaml         
            
  - title: Well overview 
    content:
      - DataTable:
          csv_file: ../grane/well_data/wellbore_overview.csv
          sorting: True
          filtering: True                  
          
  - title: Production plots  
    content:
        - TablePlotter:
            csv_file: ../grane/production_data/production_fluid_table.csv
            plot_options:
              x: 4D_interval
              y: Volumes
              type: bar   
              color: Fluid
              barmode: group
            filter_cols:
              - Well_name  
              - 4D_interval
              - Fluid  
            filter_defaults: 
              Well_name: [NO25/11-G-1Y1]  
            column_color_discrete_maps:
              Fluid:
                 Oil_[Sm3]: '#00ff00'
                 Gas_[kSm3]: '#ff0000'
                 Water_[Sm3]: '#0000ff'  
    
  - title: Injection plots  
    content:
        - TablePlotter:
            csv_file: ../grane/production_data/injection_fluid_table.csv
            plot_options:
              x: 4D_interval
              y: Volumes
              type: bar   
              color: Fluid
              barmode: group
            filter_cols:
              - Well_name  
              - 4D_interval
              - Fluid  
            filter_defaults: 
              Well_name: [NO25/11-G-4]  
            column_color_discrete_maps:
              Fluid:
                 Injected_Gas_[kSm3]: '#fa0000'
                 Injected_Water_[Sm3]: '#0000fa'                                              
          
  - title: Oil production volumes 
    content:
      - DataTable:
          csv_file: ../grane/production_data/BORE_OIL_VOL.csv  
          sorting: True
          filtering: True   
          
  - title: Gas production volumes 
    content:
      - DataTable:
          csv_file: ../grane/production_data/BORE_GAS_VOL.csv  
          sorting: True
          filtering: True       
          
  - title: Water production volumes 
    content:
      - DataTable:
          csv_file: ../grane/production_data/BORE_WAT_VOL.csv  
          sorting: True
          filtering: True             
          
  - title: Gas injection volumes 
    content:
      - DataTable:
          csv_file: ../grane/production_data/BORE_GI_VOL.csv  
          sorting: True
          filtering: True     
          
  - title: Water injection volumes  
    content:
      - DataTable:
          csv_file: ../grane/production_data/BORE_WI_VOL.csv  
          sorting: True
          filtering: True 
          
  - title: Surface with seismic cross-section
    content:
      - SurfaceWithSeismicCrossSection:
          segyfiles:
            - /scratch/ert-grane/Petek2019/gra19_r002_One2One_320real_PredReal0/realization-0/iter-0/share/observations/seismic/seismic--4d_ai_depth--20050701_19930101.segy
            - /scratch/ert-grane/Petek2019/gra19_r002_One2One_320real_PredReal0/realization-0/iter-0/share/observations/seismic/seismic--4d_ai_depth--20070701_20050701.segy
          surfacefiles:
            - /project/grane/resmod/hstruct/2019/r002/share/results/maps/topbalder--depthsurface.gri
            - /project/grane/resmod/hstruct/2019/r002/share/results/maps/toplowerheimdal--depthsurface.gri
            - /project/grane/resmod/hstruct/2019/r002/share/results/maps/toplowerlista--depthsurface.gri

          surfacenames:
            - Top Balder
            - Top Lower Heimdal
            - Top Lower Lista             
          
  - title: SEG-Y viewer
    content:
      - SegyViewer:
          segyfiles:
            - /scratch/ert-grane/Petek2019/gra19_r002_One2One_320real_PredReal0/realization-0/iter-0/share/observations/seismic/seismic--4d_ai_depth--20050701_19930101.segy     
            - /scratch/ert-grane/Petek2019/gra19_r002_One2One_320real_PredReal0/realization-0/iter-0/share/observations/seismic/seismic--4d_ai_depth--20070701_20050701.segy      
            - /scratch/ert-grane/Petek2019/gra19_r002_One2One_320real_PredReal0/realization-0/iter-0/share/observations/seismic/seismic--4d_ai_depth--20090701_20070701.segy      
            - /scratch/ert-grane/Petek2019/gra19_r002_One2One_320real_PredReal0/realization-0/iter-0/share/observations/seismic/seismic--4d_ai_depth--20110702_20090701.segy      
            - /scratch/ert-grane/Petek2019/gra19_r002_One2One_320real_PredReal0/realization-0/iter-0/share/observations/seismic/seismic--4d_ai_depth--20130702_19930101.segy      
            - /scratch/ert-grane/Petek2019/gra19_r002_One2One_320real_PredReal0/realization-0/iter-0/share/observations/seismic/seismic--4d_ai_depth--20130702_20110702.segy      
                                 
                     
  - title: Documentation
    content:  
      - Markdown:
          markdown_file: ./documentation.md
      - SyntaxHighlighter:
          filename: ./config_template.yaml
          dark_theme: yes   
      - SyntaxHighlighter:
          filename: ./settings_template.yaml
          dark_theme: yes             
           

