depth_maps:
    top_reservoir: /private/ashska/development/grane/maps/toplowerheimdal--depthsurface.gri
map_settings:
    colormaps_folder: /private/ashska/development/webviz-4d/colormaps/
    colormaps_settings: /private/ashska/development/webviz-4d/configurations/attribute_maps.csv
    default_colormap: viridis
    default_interval: 2019-09-15-2019-05-15
    attribute_settings:     
        maxpos:
            color:   dsg_spectrum
            min:    0.0
            max:    0.15
        maxneg:
            color:   geoprobe
            min: -0.05
            max:  0.05
        gasthickness:
            color:   seismic  
            min:   -5
            max:    5     
        oilthickness:
            color:   seismic
            min:    -5
            max:     5
        timeshift:
            color:   seismic 
            min: -2.0
            max:  2.0    
        
well_colors:
    default: black
    oil_open: lime
    oil_production: green
    gas_open: salmon
    gas_production: red
    gas_injection:  magenta
    water_injection: blue
    wag_injection: pink   
    planned: purple     
        
date_labels:
    20140915: PRM0
    20150515: PRM1
    20150915: PRM2
    20160515: PRM3
    20160915: PRM4    
    20170515: PRM5
    20170915: PRM6
    20180515: PRM7
    20180915: PRM8
    20190515: PRM9
    20190915: PRM10
    

    
  
     
    
