map_settings:
    default_colormap:   inferno_r

average_sgas:
    colormap:   seismic_r
    
average_soil:
    colormap:   seismic_r
    
average_swat:
    colormap:   seismic_r      
    
       
        
   
