field: 
    name: Reek

field_bounds: 
    xmin: 464241.1775462362
    ymin: 6501914.650996812
    xmax: 494042.6621086629
    ymax: 6537161.579120539
    
wells: 
    directory: /private/ashska/development/webviz-subsurface-testdata/observed_data/wells/
    tvd_cutoff: 1600        
    
map1:
    directory: /private/ashska/development/webviz-subsurface-testdata/reek_history_match/realization-0/iter-0/share/results/maps
    default_prefix: all
    default_postfix: 
    label: Simulated 4D attribute 
    default_attribute:  average_sgas
    difference: reverse  
    
map2:
    directory: /private/ashska/development/webviz-subsurface-testdata/reek_history_match/realization-0/iter-0/share/results/maps
    default_prefix: all
    default_postfix: 
    label: Simulated 4D attribute 
    default_attribute:  average_soil
    difference: reverse  
    
map3:
    directory: /private/ashska/development/webviz-subsurface-testdata/reek_history_match/realization-0/iter-0/share/results/maps
    default_prefix: all
    default_postfix: 
    label: Simulated 4D attribute 
    default_attribute:  average_swat
    difference: reverse         
       
    
map_settings:
    default_colormap:   inferno_r

average_sgas:
    colormap:   seismic_r
    
average_soil:
    colormap:   seismic_r
    
average_swat:
    colormap:   seismic_r      
    
defaults: 
    time1:  20030101
    time2:  20000101        
        
   
