- wellbore:
   name: NO 25/11-G-20 AT2
   rms_name: 25_11-G-20_AT2
   short_name: G-20AT2
   slot_name: NO 25/11-G-20
   field: Grane
   type: injection
   rkb: 69.9
   drilling_end_date: 2002-05-28T00:00:00
   fluids: gas
- interval:
    equipment: Screen
    mdBottom: 2732.94
    mdTop: 2697.96
    wellbore: NO 25/11-G-20 AT2
- interval:
    equipment: Screen
    mdBottom: 3221.1
    mdTop: 2790.44
    wellbore: NO 25/11-G-20 AT2
- interval:
    equipment: Screen
    mdBottom: 3237.17
    mdTop: 3226.14
    wellbore: NO 25/11-G-20 AT2
