- wellbore:
   name: NO 25/11-G-17 CY2T4
   rms_name: 25_11-G-17_CY2T4
   short_name: G-17CY2T4
   slot_name: NO 25/11-G-17
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2012-12-07T00:00:00
   fluids: oil
- interval:
    equipment: Screen - generic
    mdBottom: 3668.95
    mdTop: 3656.606
    wellbore: NO 25/11-G-17 CY2T4
- interval:
    equipment: Screen - generic
    mdBottom: 3693.333
    mdTop: 3680.984
    wellbore: NO 25/11-G-17 CY2T4
- interval:
    equipment: Screen - generic
    mdBottom: 3717.738
    mdTop: 3705.387
    wellbore: NO 25/11-G-17 CY2T4
- interval:
    equipment: Screen - generic
    mdBottom: 3742.123
    mdTop: 3729.779
    wellbore: NO 25/11-G-17 CY2T4
- interval:
    equipment: Screen - generic
    mdBottom: 3766.637
    mdTop: 3754.134
    wellbore: NO 25/11-G-17 CY2T4
- interval:
    equipment: Screen - generic
    mdBottom: 3791.181
    mdTop: 3778.672
    wellbore: NO 25/11-G-17 CY2T4
- interval:
    equipment: Screen - generic
    mdBottom: 3815.296
    mdTop: 3802.944
    wellbore: NO 25/11-G-17 CY2T4
- interval:
    equipment: Screen - generic
    mdBottom: 3839.689
    mdTop: 3827.333
    wellbore: NO 25/11-G-17 CY2T4
- interval:
    equipment: Screen - generic
    mdBottom: 3863.958
    mdTop: 3851.624
    wellbore: NO 25/11-G-17 CY2T4
- interval:
    equipment: Screen - generic
    mdBottom: 3887.983
    mdTop: 3875.479
    wellbore: NO 25/11-G-17 CY2T4
- interval:
    equipment: Screen - generic
    mdBottom: 3912.516
    mdTop: 3900.008
    wellbore: NO 25/11-G-17 CY2T4
- interval:
    equipment: Screen - generic
    mdBottom: 3947.303
    mdTop: 3934.782
    wellbore: NO 25/11-G-17 CY2T4
- interval:
    equipment: Screen - generic
    mdBottom: 3983.701
    mdTop: 3971.351
    wellbore: NO 25/11-G-17 CY2T4
- interval:
    equipment: Screen - generic
    mdBottom: 4020.29
    mdTop: 4007.767
    wellbore: NO 25/11-G-17 CY2T4
- interval:
    equipment: Screen - generic
    mdBottom: 4056.84
    mdTop: 4044.331
    wellbore: NO 25/11-G-17 CY2T4
- interval:
    equipment: Screen - generic
    mdBottom: 4093.249
    mdTop: 4080.729
    wellbore: NO 25/11-G-17 CY2T4
- interval:
    equipment: Screen - generic
    mdBottom: 4129.828
    mdTop: 4117.314
    wellbore: NO 25/11-G-17 CY2T4
- interval:
    equipment: Screen - generic
    mdBottom: 4228.071
    mdTop: 4141.867
    wellbore: NO 25/11-G-17 CY2T4
- interval:
    equipment: Screen - generic
    mdBottom: 4300.939
    mdTop: 4264.007
    wellbore: NO 25/11-G-17 CY2T4
- interval:
    equipment: Screen - generic
    mdBottom: 4640.474
    mdTop: 4300.939
    wellbore: NO 25/11-G-17 CY2T4
- interval:
    equipment: Screen - generic
    mdBottom: 4725.947
    mdTop: 4713.451
    wellbore: NO 25/11-G-17 CY2T4
- interval:
    equipment: Screen - generic
    mdBottom: 4750.426
    mdTop: 4737.923
    wellbore: NO 25/11-G-17 CY2T4
- interval:
    equipment: Screen - generic
    mdBottom: 4774.813
    mdTop: 4762.451
    wellbore: NO 25/11-G-17 CY2T4
- interval:
    equipment: Screen - generic
    mdBottom: 5019.914
    mdTop: 4810.91
    wellbore: NO 25/11-G-17 CY2T4
