- wellbore:
   name: NO 25/11-G-41
   rms_name: 25_11-G-41
   short_name: G-41
   slot_name: NO 25/11-G-41
   field: Grane
   type: injection
   rkb: 69.9
   drilling_end_date: 2010-06-04T00:00:00
   fluids: not applicable
