- wellbore:
   name: NO 25/11-18
   rms_name: 25_11-18
   short_name: 18
   slot_name: NO 25/11-18
   field: Grane
   type: appraisal
   rkb: 22
   drilling_end_date: 1994-10-24T00:00:00
   fluids: oil
