- wellbore:
   name: NO 25/11-G-21
   rms_name: 25_11-G-21
   short_name: G-21
   slot_name: NO 25/11-G-21
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2001-12-11T00:00:00
   fluids: oil
- interval:
    equipment: Screen
    mdBottom: 11.519999999999996
    mdTop: 0.0
    wellbore: NO 25/11-G-21
- interval:
    equipment: Screen
    mdBottom: 34.49
    mdTop: 0.0
    wellbore: NO 25/11-G-21
- interval:
    equipment: Screen
    mdBottom: 22.659999999999997
    mdTop: 0.0
    wellbore: NO 25/11-G-21
- interval:
    equipment: Screen
    mdBottom: 84.76
    mdTop: 0.0
    wellbore: NO 25/11-G-21
- interval:
    equipment: Screen
    mdBottom: 182.96
    mdTop: 0.0
    wellbore: NO 25/11-G-21
- interval:
    equipment: Screen
    mdBottom: 180.94
    mdTop: 0.0
    wellbore: NO 25/11-G-21
- interval:
    equipment: Screen
    mdBottom: 11.18
    mdTop: 0.0
    wellbore: NO 25/11-G-21
- interval:
    equipment: Screen
    mdBottom: 934.56
    mdTop: 28.28
    wellbore: NO 25/11-G-21
