- wellbore:
   name: NO 25/11-G-12 AY1T2
   rms_name: 25_11-G-12_AY1T2
   short_name: G-12AY1T2
   slot_name: NO 25/11-G-12
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2016-12-07T00:00:00
   fluids: oil
- interval:
    equipment: Screen - generic
    mdBottom: 3656.857
    mdTop: 3632.494
    wellbore: NO 25/11-G-12 AY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 3693.636
    mdTop: 3668.868
    wellbore: NO 25/11-G-12 AY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 3730.443
    mdTop: 3705.648
    wellbore: NO 25/11-G-12 AY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 3766.827
    mdTop: 3742.453
    wellbore: NO 25/11-G-12 AY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 3803.18
    mdTop: 3778.84
    wellbore: NO 25/11-G-12 AY1T2
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 3827.547
    mdTop: 3815.179
    wellbore: NO 25/11-G-12 AY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 3839.909
    mdTop: 3827.547
    wellbore: NO 25/11-G-12 AY1T2
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 3852.274
    mdTop: 3839.909
    wellbore: NO 25/11-G-12 AY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 4196.822
    mdTop: 3852.274
    wellbore: NO 25/11-G-12 AY1T2
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 4208.817
    mdTop: 4196.822
    wellbore: NO 25/11-G-12 AY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 4476.383
    mdTop: 4208.817
    wellbore: NO 25/11-G-12 AY1T2
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 4488.724
    mdTop: 4476.383
    wellbore: NO 25/11-G-12 AY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 4537.521
    mdTop: 4488.724
    wellbore: NO 25/11-G-12 AY1T2
