- wellbore:
   name: NO 25/11-G-34 AY3
   rms_name: 25_11-G-34_AY3
   short_name: G-34AY3
   slot_name: NO 25/11-G-34
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2019-01-11T00:00:00
   fluids: oil
- interval:
    equipment: Screen - generic
    mdBottom: 3271.4600000000005
    mdTop: 3247.452
    wellbore: NO 25/11-G-34 AY3
- interval:
    equipment: Screen - generic
    mdBottom: 3307.244
    mdTop: 3283.4280000000003
    wellbore: NO 25/11-G-34 AY3
- interval:
    equipment: Screen - generic
    mdBottom: 3342.871
    mdTop: 3319.2110000000002
    wellbore: NO 25/11-G-34 AY3
- interval:
    equipment: Screen - generic
    mdBottom: 3437.2580000000003
    mdTop: 3354.8350000000005
    wellbore: NO 25/11-G-34 AY3
- interval:
    equipment: Screen - generic
    mdBottom: 3449.0640000000003
    mdTop: 3437.2580000000003
    wellbore: NO 25/11-G-34 AY3
- interval:
    equipment: Screen - generic
    mdBottom: 3590.1240000000003
    mdTop: 3449.0640000000003
    wellbore: NO 25/11-G-34 AY3
