- wellbore:
   name: NO 25/11-G-11 C
   rms_name: 25_11-G-11_C
   short_name: G-11C
   slot_name: NO 25/11-G-11
   field: Grane
   type: observation
   rkb: 69.9
   drilling_end_date: 2013-06-16T00:00:00
   fluids: oil
