- wellbore:
   name: NO 25/11-G-40 AT2
   rms_name: 25_11-G-40_AT2
   short_name: G-40AT2
   slot_name: NO 25/11-G-40
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2005-09-04T00:00:00
   fluids: oil
