- wellbore:
   name: NO 25/11-G-12 Y1T2
   rms_name: 25_11-G-12_Y1T2
   short_name: G-12Y1T2
   slot_name: NO 25/11-G-12
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2006-10-18T00:00:00
   fluids: oil
