- wellbore:
   name: NO 25/11-G-30 AY1
   rms_name: 25_11-G-30_AY1
   short_name: G-30AY1
   slot_name: NO 25/11-G-30
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2017-11-04T00:00:00
   fluids: oil
