- wellbore:
   name: NO 25/11-G-21 BY1T3
   rms_name: 25_11-G-21_BY1T3
   short_name: G-21BY1T3
   slot_name: NO 25/11-G-21
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2012-04-21T00:00:00
   fluids: oil
