- wellbore:
   name: NO 25/11-G-16 Y1T2
   rms_name: 25_11-G-16_Y1T2
   short_name: G-16Y1T2
   slot_name: NO 25/11-G-16
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2008-09-13T00:00:00
   fluids: oil
