- wellbore:
   name: NO 25/11-G-1 Y2
   rms_name: 25_11-G-1_Y2
   short_name: G-1Y2
   slot_name: NO 25/11-G-1
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2008-03-05T00:00:00
   fluids: oil
