- wellbore:
   name: NO 25/11-G-29 Y2
   rms_name: 25_11-G-29_Y2
   short_name: G-29Y2
   slot_name: NO 25/11-G-29
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2017-05-24T00:00:00
   fluids: oil
- interval:
    equipment: Screen - generic
    mdBottom: 3186.215
    mdTop: 2848.329
    wellbore: NO 25/11-G-29 Y2
