- wellbore:
   name: NO 25/11-G-39 BY1
   rms_name: 25_11-G-39_BY1
   short_name: G-39BY1
   slot_name: NO 25/11-G-39
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2007-09-17T00:00:00
   fluids: oil
- interval:
    equipment: Screen - generic
    mdBottom: 5050.544
    mdTop: 4653.636
    wellbore: NO 25/11-G-39 BY1
- interval:
    equipment: Screen - generic
    mdBottom: 5458.802
    mdTop: 5056.124
    wellbore: NO 25/11-G-39 BY1
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 5470.948
    mdTop: 5458.802
    wellbore: NO 25/11-G-39 BY1
- interval:
    equipment: Screen - generic
    mdBottom: 5569.107
    mdTop: 5470.948
    wellbore: NO 25/11-G-39 BY1
- interval:
    equipment: Screen - generic
    mdBottom: 6003.919
    mdTop: 5569.107
    wellbore: NO 25/11-G-39 BY1
- interval:
    equipment: Screen - generic
    mdBottom: 6128.998
    mdTop: 6003.919
    wellbore: NO 25/11-G-39 BY1
