- wellbore:
   name: NO 25/11-G-35
   rms_name: 25_11-G-35
   short_name: G-35
   slot_name: NO 25/11-G-35
   field: Grane
   type: observation
   rkb: 69.9
   drilling_end_date: 2006-03-14T00:00:00
   fluids: not applicable
