- wellbore:
   name: NO 25/11-G-40 BY1
   rms_name: 25_11-G-40_BY1
   short_name: G-40BY1
   slot_name: NO 25/11-G-40
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2017-03-25T00:00:00
   fluids: oil
