- wellbore:
   name: NO 25/11-G-5
   rms_name: 25_11-G-5
   short_name: G-5
   slot_name: NO 25/11-G-5
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2005-03-04T00:00:00
   fluids: oil
