- wellbore:
   name: NO 25/11-G-11 A
   rms_name: 25_11-G-11_A
   short_name: G-11A
   slot_name: NO 25/11-G-11
   field: Grane
   type: observation
   rkb: 69.9
   drilling_end_date: 2013-04-03T00:00:00
   fluids: oil
