- wellbore:
   name: NO 25/11-G-16 Y3
   rms_name: 25_11-G-16_Y3
   short_name: G-16Y3
   slot_name: NO 25/11-G-16
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2008-10-18T00:00:00
   fluids: oil
