- wellbore:
   name: NO 25/11-G-17 CY1T2
   rms_name: 25_11-G-17_CY1T2
   short_name: G-17CY1T2
   slot_name: NO 25/11-G-17
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2012-10-02T00:00:00
   fluids: oil
- interval:
    equipment: Screen - generic
    mdBottom: 2987.147
    mdTop: 2975.137
    wellbore: NO 25/11-G-17 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 3010.692
    mdTop: 2998.682
    wellbore: NO 25/11-G-17 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 3034.757
    mdTop: 3022.737
    wellbore: NO 25/11-G-17 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 3058.731
    mdTop: 3046.801
    wellbore: NO 25/11-G-17 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 3081.757
    mdTop: 3070.577
    wellbore: NO 25/11-G-17 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 3105.811
    mdTop: 3093.801
    wellbore: NO 25/11-G-17 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 3129.865
    mdTop: 3117.855
    wellbore: NO 25/11-G-17 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 3165.931
    mdTop: 3141.911
    wellbore: NO 25/11-G-17 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 3202.51
    mdTop: 3178.49
    wellbore: NO 25/11-G-17 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 3561.906
    mdTop: 3537.986
    wellbore: NO 25/11-G-17 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 3597.973
    mdTop: 3573.953
    wellbore: NO 25/11-G-17 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 3634.041
    mdTop: 3610.021
    wellbore: NO 25/11-G-17 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 3682.173
    mdTop: 3658.133
    wellbore: NO 25/11-G-17 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 3717.438
    mdTop: 3694.218
    wellbore: NO 25/11-G-17 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 3753.52
    mdTop: 3729.48
    wellbore: NO 25/11-G-17 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 3789.518
    mdTop: 3765.478
    wellbore: NO 25/11-G-17 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 3836.988
    mdTop: 3812.948
    wellbore: NO 25/11-G-17 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 3873.073
    mdTop: 3849.033
    wellbore: NO 25/11-G-17 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 3909.161
    mdTop: 3885.121
    wellbore: NO 25/11-G-17 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 3944.849
    mdTop: 3920.889
    wellbore: NO 25/11-G-17 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 3980.835
    mdTop: 3956.895
    wellbore: NO 25/11-G-17 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 4053.211
    mdTop: 4005.241
    wellbore: NO 25/11-G-17 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 4269.637
    mdTop: 4065.377
    wellbore: NO 25/11-G-17 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 2766.363
    mdTop: 2301.69
    wellbore: NO 25/11-G-17 CY1T2
