- wellbore:
   name: NO 25/11-G-38 T4
   rms_name: 25_11-G-38_T4
   short_name: G-38T4
   slot_name: NO 25/11-G-38
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2011-03-08T00:00:00
   fluids: oil
