- wellbore:
   name: NO 25/11-G-8 A
   rms_name: 25_11-G-8_A
   short_name: G-8A
   slot_name: NO 25/11-G-8
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2015-07-19T00:00:00
   fluids: not applicable
