- wellbore:
   name: NO 25/11-G-31 T2
   rms_name: 25_11-G-31_T2
   short_name: G-31T2
   slot_name: NO 25/11-G-31
   field: Grane
   type: observation
   rkb: 69.9
   drilling_end_date: 2015-09-20T00:00:00
   fluids: oil
