- wellbore:
   name: NO 25/11-G-29
   rms_name: 25_11-G-29
   short_name: G-29
   slot_name: NO 25/11-G-29
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2017-05-19T00:00:00
   fluids: oil
- interval:
    equipment: Screen - generic
    mdBottom: 2611.408
    mdTop: 2272.76
    wellbore: NO 25/11-G-29
- interval:
    equipment: Screen - generic
    mdBottom: 2623.432
    mdTop: 2611.408
    wellbore: NO 25/11-G-29
- interval:
    equipment: Screen - generic
    mdBottom: 2659.831
    mdTop: 2647.493
    wellbore: NO 25/11-G-29
- interval:
    equipment: Screen - generic
    mdBottom: 2708.73
    mdTop: 2696.388
    wellbore: NO 25/11-G-29
- interval:
    equipment: Screen - generic
    mdBottom: 2770.494
    mdTop: 2758.117
    wellbore: NO 25/11-G-29
