- wellbore:
   name: NO 25/11-G-30 AY2
   rms_name: 25_11-G-30_AY2
   short_name: G-30AY2
   slot_name: NO 25/11-G-30
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2017-11-15T00:00:00
   fluids: oil
- interval:
    equipment: Screen - generic
    mdBottom: 3580.442
    mdTop: 3546.545
    wellbore: NO 25/11-G-30 AY2
- interval:
    equipment: Screen - generic
    mdBottom: 3603.664
    mdTop: 3592.466
    wellbore: NO 25/11-G-30 AY2
- interval:
    equipment: Screen - generic
    mdBottom: 3627.002
    mdTop: 3615.662
    wellbore: NO 25/11-G-30 AY2
- interval:
    equipment: Screen - generic
    mdBottom: 3649.713
    mdTop: 3638.002
    wellbore: NO 25/11-G-30 AY2
- interval:
    equipment: Screen - generic
    mdBottom: 3822.862
    mdTop: 3661.754
    wellbore: NO 25/11-G-30 AY2
