- wellbore:
   name: NO 25/11-G-3 AY1
   rms_name: 25_11-G-3_AY1
   short_name: G-3AY1
   slot_name: NO 25/11-G-3
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2010-02-12T00:00:00
   fluids: oil
