- wellbore:
   name: NO 25/11-21 S
   rms_name: 25_11-21_S
   short_name: 21S
   slot_name: NO 25/11-21
   field: Grane
   type: appraisal
   rkb: 26
   drilling_end_date: 1995-11-14T00:00:00
   fluids: oil
