- wellbore:
   name: NO 25/11-G-7 CY1
   rms_name: 25_11-G-7_CY1
   short_name: G-7CY1
   slot_name: NO 25/11-G-7
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2019-11-19T00:00:00
   fluids: oil
