- wellbore:
   name: NO 25/11-G-21 A
   rms_name: 25_11-G-21_A
   short_name: G-21A
   slot_name: NO 25/11-G-21
   field: Grane
   type: observation
   rkb: 69.9
   drilling_end_date: 2012-03-27T00:00:00
   fluids: oil
