- wellbore:
   name: NO 25/11-G-2 BY2
   rms_name: 25_11-G-2_BY2
   short_name: G-2BY2
   slot_name: NO 25/11-G-2
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2015-04-23T00:00:00
   fluids: oil
- interval:
    equipment: Screen
    mdBottom: 5019.94
    mdTop: 5007.52
    wellbore: NO 25/11-G-2 BY2
- interval:
    equipment: Screen
    mdBottom: 5463.49
    mdTop: 5031.93
    wellbore: NO 25/11-G-2 BY2
- interval:
    equipment: Screen
    mdBottom: 4652.33
    mdTop: 4155.94
    wellbore: NO 25/11-G-2 BY2
- interval:
    equipment: Screen
    mdBottom: 4848.99
    mdTop: 4652.33
    wellbore: NO 25/11-G-2 BY2
- interval:
    equipment: Screen
    mdBottom: 4873.43
    mdTop: 4860.99
    wellbore: NO 25/11-G-2 BY2
- interval:
    equipment: Screen
    mdBottom: 4897.81
    mdTop: 4885.43
    wellbore: NO 25/11-G-2 BY2
- interval:
    equipment: Screen
    mdBottom: 4922.18
    mdTop: 4909.81
    wellbore: NO 25/11-G-2 BY2
- interval:
    equipment: Screen
    mdBottom: 4946.57
    mdTop: 4934.18
    wellbore: NO 25/11-G-2 BY2
- interval:
    equipment: Screen
    mdBottom: 4971.01
    mdTop: 4958.58
    wellbore: NO 25/11-G-2 BY2
- interval:
    equipment: Screen
    mdBottom: 4995.51
    mdTop: 4983.01
    wellbore: NO 25/11-G-2 BY2
