- wellbore:
   name: NO 25/11-G-31 BY1T2
   rms_name: 25_11-G-31_BY1T2
   short_name: G-31BY1T2
   slot_name: NO 25/11-G-31
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2016-05-10T00:00:00
   fluids: oil
