- wellbore:
   name: NO 25/11-G-39 BY2
   rms_name: 25_11-G-39_BY2
   short_name: G-39BY2
   slot_name: NO 25/11-G-39
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2007-10-23T00:00:00
   fluids: oil
- interval:
    equipment: Screen - generic
    mdBottom: 4943.904
    mdTop: 4547.864
    wellbore: NO 25/11-G-39 BY2
- interval:
    equipment: Screen - generic
    mdBottom: 5469.256
    mdTop: 4949.734
    wellbore: NO 25/11-G-39 BY2
- interval:
    equipment: Screen - generic
    mdBottom: 6352.146
    mdTop: 5469.256
    wellbore: NO 25/11-G-39 BY2
- interval:
    equipment: Screen - generic
    mdBottom: 6651.185
    mdTop: 6352.146
    wellbore: NO 25/11-G-39 BY2
