- wellbore:
   name: NO 25/11-G-3 T3
   rms_name: 25_11-G-3_T3
   short_name: G-3T3
   slot_name: NO 25/11-G-3
   field: Grane
   type: observation
   rkb: 69.9
   drilling_end_date: 2010-01-21T00:00:00
   fluids: oil
