- wellbore:
   name: NO 25/11-G-11 BY1T3
   rms_name: 25_11-G-11_BY1T3
   short_name: G-11BY1T3
   slot_name: NO 25/11-G-11
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2013-05-17T00:00:00
   fluids: oil
