- wellbore:
   name: NO 25/11-G-19 A
   rms_name: 25_11-G-19_A
   short_name: G-19A
   slot_name: NO 25/11-G-19
   field: Grane
   type: observation
   rkb: 69.9
   drilling_end_date: 2014-07-15T00:00:00
   fluids: oil
