- wellbore:
   name: NO 25/11-G-7 AY2T4
   rms_name: 25_11-G-7_AY2T4
   short_name: G-7AY2T4
   slot_name: NO 25/11-G-7
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2010-10-27T00:00:00
   fluids: oil
- interval:
    equipment: Screen
    mdBottom: 4581.467
    mdTop: 4569.626
    wellbore: NO 25/11-G-7 AY2T4
- interval:
    equipment: Screen
    mdBottom: 4791.34
    mdTop: 4581.467
    wellbore: NO 25/11-G-7 AY2T4
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 4803.853
    mdTop: 4791.34
    wellbore: NO 25/11-G-7 AY2T4
- interval:
    equipment: Screen
    mdBottom: 5204.197
    mdTop: 5191.828
    wellbore: NO 25/11-G-7 AY2T4
- interval:
    equipment: Screen
    mdBottom: 5780.743
    mdTop: 5204.197
    wellbore: NO 25/11-G-7 AY2T4
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 5793.118
    mdTop: 5780.743
    wellbore: NO 25/11-G-7 AY2T4
- interval:
    equipment: Screen
    mdBottom: 5805.542
    mdTop: 5793.118
    wellbore: NO 25/11-G-7 AY2T4
- interval:
    equipment: Screen
    mdBottom: 6590.152
    mdTop: 5805.542
    wellbore: NO 25/11-G-7 AY2T4
- interval:
    equipment: Screen
    mdBottom: 6675.408
    mdTop: 6590.152
    wellbore: NO 25/11-G-7 AY2T4
- interval:
    equipment: Screen
    mdBottom: 6687.649
    mdTop: 6675.408
    wellbore: NO 25/11-G-7 AY2T4
