- wellbore:
   name: NO 25/11-G-22 BY1
   rms_name: 25_11-G-22_BY1
   short_name: G-22BY1
   slot_name: NO 25/11-G-22
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2016-03-01T00:00:00
   fluids: oil
