- wellbore:
   name: NO 25/11-G-34 AY2
   rms_name: 25_11-G-34_AY2
   short_name: G-34AY2
   slot_name: NO 25/11-G-34
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2018-12-31T00:00:00
   fluids: oil
- interval:
    equipment: Screen - generic
    mdBottom: 3139.186
    mdTop: 3115.5110000000004
    wellbore: NO 25/11-G-34 AY2
- interval:
    equipment: Screen - generic
    mdBottom: 3158.505
    mdTop: 3146.496
    wellbore: NO 25/11-G-34 AY2
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 3170.2650000000003
    mdTop: 3158.505
    wellbore: NO 25/11-G-34 AY2
- interval:
    equipment: Screen - generic
    mdBottom: 3278.1360000000004
    mdTop: 3170.2650000000003
    wellbore: NO 25/11-G-34 AY2
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 3290.132
    mdTop: 3278.1360000000004
    wellbore: NO 25/11-G-34 AY2
- interval:
    equipment: Screen - generic
    mdBottom: 3433.5350000000003
    mdTop: 3290.132
    wellbore: NO 25/11-G-34 AY2
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 3445.452
    mdTop: 3433.5350000000003
    wellbore: NO 25/11-G-34 AY2
- interval:
    equipment: Screen - generic
    mdBottom: 3774.8210000000004
    mdTop: 3445.452
    wellbore: NO 25/11-G-34 AY2
- interval:
    equipment: Screen - generic
    mdBottom: 3927.824
    mdTop: 3774.8210000000004
    wellbore: NO 25/11-G-34 AY2
