- wellbore:
   name: NO 25/11-G-7
   rms_name: 25_11-G-7
   short_name: G-7
   slot_name: NO 25/11-G-7
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2010-08-16T00:00:00
   fluids: not applicable
