- wellbore:
   name: NO 25/11-G-5 CY3
   rms_name: 25_11-G-5_CY3
   short_name: G-5CY3
   slot_name: NO 25/11-G-5
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2019-04-12T00:00:00
   fluids: oil
