- wellbore:
   name: NO 25/11-G-20
   rms_name: 25_11-G-20
   short_name: G-20
   slot_name: NO 25/11-G-20
   field: Grane
   type: observation
   rkb: 69.9
   drilling_end_date: 2002-04-22T00:00:00
   fluids: not applicable
