- wellbore:
   name: NO 25/11-G-25 T2
   rms_name: 25_11-G-25_T2
   short_name: G-25T2
   slot_name: NO 25/11-G-25
   field: Grane
   type: production
   rkb: 26
   drilling_end_date: 2002-08-06T00:00:00
   fluids: oil
- interval:
    equipment: Screen
    mdBottom: 2234.935
    mdTop: 2057.845
    wellbore: NO 25/11-G-25 T2
- interval:
    equipment: Screen
    mdBottom: 2515.805
    mdTop: 2246.9249999999997
    wellbore: NO 25/11-G-25 T2
- interval:
    equipment: Screen
    mdBottom: 2858.495
    mdTop: 2527.795
    wellbore: NO 25/11-G-25 T2
- interval:
    equipment: Screen
    mdBottom: 3105.605
    mdTop: 2869.9249999999997
    wellbore: NO 25/11-G-25 T2
- interval:
    equipment: Screen
    mdBottom: 3142.275
    mdTop: 3106.605
    wellbore: NO 25/11-G-25 T2
- interval:
    equipment: Screen
    mdBottom: 3365.485
    mdTop: 3154.275
    wellbore: NO 25/11-G-25 T2
- interval:
    equipment: Screen
    mdBottom: 3554.805
    mdTop: 3377.475
    wellbore: NO 25/11-G-25 T2
- interval:
    equipment: Screen
    mdBottom: 3591.575
    mdTop: 3555.805
    wellbore: NO 25/11-G-25 T2
- interval:
    equipment: Screen
    mdBottom: 3615.025
    mdTop: 3603.035
    wellbore: NO 25/11-G-25 T2
