- wellbore:
   name: NO 25/11-G-5 CY1
   rms_name: 25_11-G-5_CY1
   short_name: G-5CY1
   slot_name: NO 25/11-G-5
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2019-02-22T00:00:00
   fluids: oil
