- wellbore:
   name: NO 25/11-G-6 AY3
   rms_name: 25_11-G-6_AY3
   short_name: G-6AY3
   slot_name: NO 25/11-G-6
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2016-08-10T00:00:00
   fluids: oil
- interval:
    equipment: Screen - generic
    mdBottom: 2830.515
    mdTop: 2818.21
    wellbore: NO 25/11-G-6 AY3
- interval:
    equipment: Screen - generic
    mdBottom: 2866.79
    mdTop: 2841.998
    wellbore: NO 25/11-G-6 AY3
- interval:
    equipment: Screen - generic
    mdBottom: 2903.16
    mdTop: 2878.804
    wellbore: NO 25/11-G-6 AY3
- interval:
    equipment: Screen - generic
    mdBottom: 2939.536
    mdTop: 2915.169
    wellbore: NO 25/11-G-6 AY3
- interval:
    equipment: Screen - generic
    mdBottom: 2975.461
    mdTop: 2951.092
    wellbore: NO 25/11-G-6 AY3
- interval:
    equipment: Screen - generic
    mdBottom: 3012.404
    mdTop: 2987.469
    wellbore: NO 25/11-G-6 AY3
- interval:
    equipment: Screen - generic
    mdBottom: 3049.234
    mdTop: 3024.415
    wellbore: NO 25/11-G-6 AY3
- interval:
    equipment: Screen - generic
    mdBottom: 3086.012
    mdTop: 3061.25
    wellbore: NO 25/11-G-6 AY3
- interval:
    equipment: Screen - generic
    mdBottom: 3110.376
    mdTop: 3098.018
    wellbore: NO 25/11-G-6 AY3
- interval:
    equipment: Screen - generic
    mdBottom: 3134.727
    mdTop: 3122.389
    wellbore: NO 25/11-G-6 AY3
- interval:
    equipment: Screen - generic
    mdBottom: 3159.261
    mdTop: 3146.735
    wellbore: NO 25/11-G-6 AY3
- interval:
    equipment: Screen - generic
    mdBottom: 3183.797
    mdTop: 3171.275
    wellbore: NO 25/11-G-6 AY3
- interval:
    equipment: Screen - generic
    mdBottom: 3207.91
    mdTop: 3195.392
    wellbore: NO 25/11-G-6 AY3
- interval:
    equipment: Screen - generic
    mdBottom: 3243.927
    mdTop: 3231.421
    wellbore: NO 25/11-G-6 AY3
- interval:
    equipment: Screen - generic
    mdBottom: 3280.291
    mdTop: 3267.951
    wellbore: NO 25/11-G-6 AY3
- interval:
    equipment: Screen - generic
    mdBottom: 3316.66
    mdTop: 3304.303
    wellbore: NO 25/11-G-6 AY3
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 3353.02
    mdTop: 3340.667
    wellbore: NO 25/11-G-6 AY3
- interval:
    equipment: Screen - generic
    mdBottom: 3388.473
    mdTop: 3365.027
    wellbore: NO 25/11-G-6 AY3
- interval:
    equipment: Screen - generic
    mdBottom: 3412.853
    mdTop: 3400.485
    wellbore: NO 25/11-G-6 AY3
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 3425.264
    mdTop: 3412.853
    wellbore: NO 25/11-G-6 AY3
- interval:
    equipment: Screen - generic
    mdBottom: 3449.89
    mdTop: 3425.264
    wellbore: NO 25/11-G-6 AY3
- interval:
    equipment: Screen - generic
    mdBottom: 3470.621
    mdTop: 3458.105
    wellbore: NO 25/11-G-6 AY3
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 3482.863
    mdTop: 3470.621
    wellbore: NO 25/11-G-6 AY3
- interval:
    equipment: Screen - generic
    mdBottom: 3716.174
    mdTop: 3482.863
    wellbore: NO 25/11-G-6 AY3
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 3728.176
    mdTop: 3716.174
    wellbore: NO 25/11-G-6 AY3
- interval:
    equipment: Screen - generic
    mdBottom: 4473.422
    mdTop: 3773.464
    wellbore: NO 25/11-G-6 AY3
