- wellbore:
   name: NO 25/11-G-3
   rms_name: 25_11-G-3
   short_name: G-3
   slot_name: NO 25/11-G-3
   field: Grane
   type: observation
   rkb: 69.9
   drilling_end_date: 2010-01-25T00:00:00
   fluids: oil
