- wellbore:
   name: NO 25/11-G-2 BY1T2
   rms_name: 25_11-G-2_BY1T2
   short_name: G-2BY1T2
   slot_name: NO 25/11-G-2
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2015-04-04T00:00:00
   fluids: oil
