- wellbore:
   name: NO 25/11-G-2 A
   rms_name: 25_11-G-2_A
   short_name: G-2A
   slot_name: NO 25/11-G-2
   field: Grane
   type: observation
   rkb: 69.9
   drilling_end_date: 2015-03-21T00:00:00
   fluids: oil
