- wellbore:
   name: NO 25/11-G-6 AY2
   rms_name: 25_11-G-6_AY2
   short_name: G-6AY2
   slot_name: NO 25/11-G-6
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2016-08-06T00:00:00
   fluids: oil
- interval:
    equipment: Screen - generic
    mdBottom: 4151.961
    mdTop: 3695.089
    wellbore: NO 25/11-G-6 AY2
