- wellbore:
   name: NO 25/11-G-38 AY1T2
   rms_name: 25_11-G-38_AY1T2
   short_name: G-38AY1T2
   slot_name: NO 25/11-G-38
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2011-04-24T00:00:00
   fluids: oil
- interval:
    equipment: Screen
    mdBottom: 4885.214
    mdTop: 4477.702
    wellbore: NO 25/11-G-38 AY1T2
- interval:
    equipment: Screen
    mdBottom: 5119.453
    mdTop: 4934.621
    wellbore: NO 25/11-G-38 AY1T2
- interval:
    equipment: Screen
    mdBottom: 6398.22
    mdTop: 5623.63
    wellbore: NO 25/11-G-38 AY1T2
