- wellbore:
   name: NO 25/11-G-8 BY2T2
   rms_name: 25_11-G-8_BY2T2
   short_name: G-8BY2T2
   slot_name: NO 25/11-G-8
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2015-08-04T00:00:00
   fluids: oil
- interval:
    equipment: Screen - generic
    mdBottom: 3828.486
    mdTop: 3690.959
    wellbore: NO 25/11-G-8 BY2T2
- interval:
    equipment: Screen - generic
    mdBottom: 4058.874
    mdTop: 3828.486
    wellbore: NO 25/11-G-8 BY2T2
