- wellbore:
   name: NO 25/11-G-13 B
   rms_name: 25_11-G-13_B
   short_name: G-13B
   slot_name: NO 25/11-G-13
   field: Grane
   type: observation
   rkb: 69.9
   drilling_end_date: 2009-08-30T00:00:00
   fluids: not applicable
