- wellbore:
   name: NO 25/11-G-7 AY3T3
   rms_name: 25_11-G-7_AY3T3
   short_name: G-7AY3T3
   slot_name: NO 25/11-G-7
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2010-11-13T00:00:00
   fluids: oil
- interval:
    equipment: Screen
    mdBottom: 4999.199
    mdTop: 4812.219
    wellbore: NO 25/11-G-7 AY3T3
- interval:
    equipment: Screen
    mdBottom: 5011.715
    mdTop: 4999.199
    wellbore: NO 25/11-G-7 AY3T3
- interval:
    equipment: Screen
    mdBottom: 5024.232
    mdTop: 5011.715
    wellbore: NO 25/11-G-7 AY3T3
- interval:
    equipment: Screen
    mdBottom: 5311.134
    mdTop: 5024.232
    wellbore: NO 25/11-G-7 AY3T3
- interval:
    equipment: Screen
    mdBottom: 5323.496
    mdTop: 5311.134
    wellbore: NO 25/11-G-7 AY3T3
- interval:
    equipment: Screen
    mdBottom: 5731.971
    mdTop: 5323.496
    wellbore: NO 25/11-G-7 AY3T3
- interval:
    equipment: Screen
    mdBottom: 5878.969
    mdTop: 5731.971
    wellbore: NO 25/11-G-7 AY3T3
- interval:
    equipment: Screen
    mdBottom: 5891.334
    mdTop: 5878.969
    wellbore: NO 25/11-G-7 AY3T3
- interval:
    equipment: Screen
    mdBottom: 5916.086
    mdTop: 5891.334
    wellbore: NO 25/11-G-7 AY3T3
