- wellbore:
   name: NO 25/11-G-35 A
   rms_name: 25_11-G-35_A
   short_name: G-35A
   slot_name: NO 25/11-G-35
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2006-04-06T00:00:00
   fluids: oil
