- wellbore:
   name: NO 25/11-G-18 AY1
   rms_name: 25_11-G-18_AY1
   short_name: G-18AY1
   slot_name: NO 25/11-G-18
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2017-01-27T00:00:00
   fluids: oil
- interval:
    equipment: Screen - generic
    mdBottom: 2484.064
    mdTop: 2399.114
    wellbore: NO 25/11-G-18 AY1
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 2496.086
    mdTop: 2484.064
    wellbore: NO 25/11-G-18 AY1
- interval:
    equipment: Screen - generic
    mdBottom: 2581.233
    mdTop: 2496.086
    wellbore: NO 25/11-G-18 AY1
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 2593.664
    mdTop: 2581.233
    wellbore: NO 25/11-G-18 AY1
- interval:
    equipment: Screen - generic
    mdBottom: 2617.332
    mdTop: 2593.664
    wellbore: NO 25/11-G-18 AY1
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 2629.769
    mdTop: 2617.332
    wellbore: NO 25/11-G-18 AY1
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 2666.948
    mdTop: 2629.769
    wellbore: NO 25/11-G-18 AY1
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 2679.445
    mdTop: 2666.948
    wellbore: NO 25/11-G-18 AY1
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 2790.449
    mdTop: 2679.445
    wellbore: NO 25/11-G-18 AY1
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 2802.812
    mdTop: 2790.449
    wellbore: NO 25/11-G-18 AY1
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 2986.885
    mdTop: 2802.812
    wellbore: NO 25/11-G-18 AY1
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 2999.209
    mdTop: 2986.885
    wellbore: NO 25/11-G-18 AY1
- interval:
    equipment: Screen - generic
    mdBottom: 3398.441
    mdTop: 2999.209
    wellbore: NO 25/11-G-18 AY1
