- wellbore:
   name: NO 25/11-G-19 D
   rms_name: 25_11-G-19_D
   short_name: G-19D
   slot_name: NO 25/11-G-19
   field: Grane
   type: observation
   rkb: 69.9
   drilling_end_date: 2014-07-29T00:00:00
   fluids: oil
