- wellbore:
   name: NO 25/11-G-39 CY1
   rms_name: 25_11-G-39_CY1
   short_name: G-39CY1
   slot_name: NO 25/11-G-39
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2018-02-06T00:00:00
   fluids: oil
