- wellbore:
   name: NO 25/11-G-35 BY3T2
   rms_name: 25_11-G-35_BY3T2
   short_name: G-35BY3T2
   slot_name: NO 25/11-G-35
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2018-11-01T00:00:00
   fluids: oil
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 2519.309
    mdTop: 2507.316
    wellbore: NO 25/11-G-35 BY3T2
- interval:
    equipment: Screen - generic
    mdBottom: 2555.131
    mdTop: 2519.309
    wellbore: NO 25/11-G-35 BY3T2
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 2567.132
    mdTop: 2555.131
    wellbore: NO 25/11-G-35 BY3T2
- interval:
    equipment: Screen - generic
    mdBottom: 2937.101
    mdTop: 2567.132
    wellbore: NO 25/11-G-35 BY3T2
