- wellbore:
   name: NO 25/11-G-4
   rms_name: 25_11-G-4
   short_name: G-4
   slot_name: NO 25/11-G-4
   field: Grane
   type: injection
   rkb: 69.9
   drilling_end_date: 2015-01-12T00:00:00
   fluids: gas
