- wellbore:
   name: NO 25/11-G-3 AY1T2
   rms_name: 25_11-G-3_AY1T2
   short_name: G-3AY1T2
   slot_name: NO 25/11-G-3
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2010-02-11T00:00:00
   fluids: oil
- interval:
    equipment: Screen & Blank Pipe - generic
    mdBottom: 3664.078
    mdTop: 3576.43
    wellbore: NO 25/11-G-3 AY1T2
- interval:
    equipment: Screen
    mdBottom: 4237.957
    mdTop: 3714.12
    wellbore: NO 25/11-G-3 AY1T2
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 4250.461
    mdTop: 4237.957
    wellbore: NO 25/11-G-3 AY1T2
- interval:
    equipment: Screen & Blank Pipe - generic
    mdBottom: 4487.117
    mdTop: 4275.489
    wellbore: NO 25/11-G-3 AY1T2
- interval:
    equipment: Screen & Blank Pipe - generic
    mdBottom: 4798.669
    mdTop: 4524.662
    wellbore: NO 25/11-G-3 AY1T2
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 4811.182
    mdTop: 4798.669
    wellbore: NO 25/11-G-3 AY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 5095.412
    mdTop: 4811.182
    wellbore: NO 25/11-G-3 AY1T2
