- wellbore:
   name: NO 25/11-G-1 Y3T2
   rms_name: 25_11-G-1_Y3T2
   short_name: G-1Y3T2
   slot_name: NO 25/11-G-1
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2008-03-30T00:00:00
   fluids: oil
- interval:
    equipment: Screen - generic
    mdBottom: 4901.81
    mdTop: 4401.389
    wellbore: NO 25/11-G-1 Y3T2
- interval:
    equipment: Screen - generic
    mdBottom: 4988.933
    mdTop: 4901.81
    wellbore: NO 25/11-G-1 Y3T2
- interval:
    equipment: Screen - generic
    mdBottom: 5560.552
    mdTop: 4988.933
    wellbore: NO 25/11-G-1 Y3T2
