- wellbore:
   name: NO 25/11-G-7 AY1T2
   rms_name: 25_11-G-7_AY1T2
   short_name: G-7AY1T2
   slot_name: NO 25/11-G-7
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2010-09-13T00:00:00
   fluids: oil
- interval:
    equipment: Screen
    mdBottom: 4558.149
    mdTop: 4545.792
    wellbore: NO 25/11-G-7 AY1T2
- interval:
    equipment: Screen
    mdBottom: 5226.113
    mdTop: 4558.149
    wellbore: NO 25/11-G-7 AY1T2
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 5238.625
    mdTop: 5226.113
    wellbore: NO 25/11-G-7 AY1T2
- interval:
    equipment: Screen
    mdBottom: 5249.91
    mdTop: 5238.625
    wellbore: NO 25/11-G-7 AY1T2
- interval:
    equipment: Screen
    mdBottom: 5790.989
    mdTop: 5249.91
    wellbore: NO 25/11-G-7 AY1T2
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 5803.402
    mdTop: 5790.989
    wellbore: NO 25/11-G-7 AY1T2
- interval:
    equipment: Screen
    mdBottom: 5815.841
    mdTop: 5803.402
    wellbore: NO 25/11-G-7 AY1T2
- interval:
    equipment: Screen
    mdBottom: 6661.518
    mdTop: 5815.841
    wellbore: NO 25/11-G-7 AY1T2
