- wellbore:
   name: NO 25/11-G-8 BY1T2
   rms_name: 25_11-G-8_BY1T2
   short_name: G-8BY1T2
   slot_name: NO 25/11-G-8
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2015-08-17T00:00:00
   fluids: oil
- interval:
    equipment: Screen - generic
    mdBottom: 3446.619
    mdTop: 3029.275
    wellbore: NO 25/11-G-8 BY1T2
