- wellbore:
   name: NO 25/11-G-34
   rms_name: 25_11-G-34
   short_name: G-34
   slot_name: NO 25/11-G-34
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2005-07-11T00:00:00
   fluids: oil
- interval:
    equipment: Screen
    mdBottom: 2868.031
    mdTop: 2669.612
    wellbore: NO 25/11-G-34
- interval:
    equipment: Screen
    mdBottom: 3069.695
    mdTop: 2870.841
    wellbore: NO 25/11-G-34
- interval:
    equipment: Screen
    mdBottom: 3267.925
    mdTop: 3069.695
    wellbore: NO 25/11-G-34
