- wellbore:
   name: NO 25/11-G-16 AY2
   rms_name: 25_11-G-16_AY2
   short_name: G-16AY2
   slot_name: NO 25/11-G-16
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2017-08-21T00:00:00
   fluids: oil
- interval:
    equipment: Screen - generic
    mdBottom: 3838.119
    mdTop: 3826.063
    wellbore: NO 25/11-G-16 AY2
- interval:
    equipment: Screen - generic
    mdBottom: 3873.205
    mdTop: 3849.446
    wellbore: NO 25/11-G-16 AY2
- interval:
    equipment: Screen - generic
    mdBottom: 3909.292
    mdTop: 3885.205
    wellbore: NO 25/11-G-16 AY2
- interval:
    equipment: Screen - generic
    mdBottom: 3945.248
    mdTop: 3921.171
    wellbore: NO 25/11-G-16 AY2
- interval:
    equipment: Screen - generic
    mdBottom: 3981.045
    mdTop: 3957.25
    wellbore: NO 25/11-G-16 AY2
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 4004.931
    mdTop: 3993.058
    wellbore: NO 25/11-G-16 AY2
- interval:
    equipment: Screen - generic
    mdBottom: 4149.031
    mdTop: 4004.931
    wellbore: NO 25/11-G-16 AY2
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 4160.862
    mdTop: 4149.031
    wellbore: NO 25/11-G-16 AY2
- interval:
    equipment: Screen - generic
    mdBottom: 4495.203
    mdTop: 4160.862
    wellbore: NO 25/11-G-16 AY2
