- wellbore:
   name: NO 25/11-G-15 AY3
   rms_name: 25_11-G-15_AY3
   short_name: G-15AY3
   slot_name: NO 25/11-G-15
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2009-02-20T00:00:00
   fluids: oil
