- wellbore:
   name: NO 25/11-G-13 Y1
   rms_name: 25_11-G-13_Y1
   short_name: G-13Y1
   slot_name: NO 25/11-G-13
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2009-07-22T00:00:00
   fluids: oil
