- wellbore:
   name: NO 25/11-G-15 AY3T4
   rms_name: 25_11-G-15_AY3T4
   short_name: G-15AY3T4
   slot_name: NO 25/11-G-15
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2010-10-17T00:00:00
   fluids: oil
- interval:
    equipment: Screen & Blank Pipe - generic
    mdBottom: 3467.39
    mdTop: 3005.693
    wellbore: NO 25/11-G-15 AY3T4
- interval:
    equipment: Screen
    mdBottom: 3492.464
    mdTop: 3479.947
    wellbore: NO 25/11-G-15 AY3T4
- interval:
    equipment: Screen & Blank Pipe - generic
    mdBottom: 4387.77
    mdTop: 3505.019
    wellbore: NO 25/11-G-15 AY3T4
- interval:
    equipment: Screen
    mdBottom: 4833.898
    mdTop: 4387.77
    wellbore: NO 25/11-G-15 AY3T4
