- wellbore:
   name: NO 25/11-G-33
   rms_name: 25_11-G-33
   short_name: G-33
   slot_name: NO 25/11-G-33
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2010-05-03T00:00:00
   fluids: 
