- wellbore:
   name: NO 25/11-G-17 B
   rms_name: 25_11-G-17_B
   short_name: G-17B
   slot_name: NO 25/11-G-17
   field: Grane
   type: observation
   rkb: 69.9
   drilling_end_date: 2012-09-02T00:00:00
   fluids: oil
