- wellbore:
   name: NO 25/11-G-30 Y1
   rms_name: 25_11-G-30_Y1
   short_name: G-30Y1
   slot_name: NO 25/11-G-30
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2007-01-17T00:00:00
   fluids: oil
- interval:
    equipment: Screen
    mdBottom: 3185.04
    mdTop: 2551.721
    wellbore: NO 25/11-G-30 Y1
- interval:
    equipment: Screen
    mdBottom: 3204.577
    mdTop: 3192.07
    wellbore: NO 25/11-G-30 Y1
