- wellbore:
   name: NO 25/11-G-39 CY3
   rms_name: 25_11-G-39_CY3
   short_name: G-39CY3
   slot_name: NO 25/11-G-39
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2018-03-15T00:00:00
   fluids: oil
