- wellbore:
   name: NO 25/11-G-25
   rms_name: 25_11-G-25
   short_name: G-25
   slot_name: NO 25/11-G-25
   field: Grane
   type: production
   rkb: 26
   drilling_end_date: 2002-08-04T00:00:00
   fluids: oil
