- wellbore:
   name: NO 25/11-G-11 BY1T4
   rms_name: 25_11-G-11_BY1T4
   short_name: G-11BY1T4
   slot_name: NO 25/11-G-11
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2013-06-02T00:00:00
   fluids: oil
- interval:
    equipment: Screen - generic
    mdBottom: 3929.786
    mdTop: 3843.166
    wellbore: NO 25/11-G-11 BY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 4052.632
    mdTop: 3929.786
    wellbore: NO 25/11-G-11 BY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 4210.57
    mdTop: 4052.632
    wellbore: NO 25/11-G-11 BY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 3313.673
    mdTop: 3301.324
    wellbore: NO 25/11-G-11 BY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 3338.239
    mdTop: 3325.722
    wellbore: NO 25/11-G-11 BY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 3362.176
    mdTop: 3350.279
    wellbore: NO 25/11-G-11 BY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 3386.212
    mdTop: 3373.703
    wellbore: NO 25/11-G-11 BY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 3410.267
    mdTop: 3398.239
    wellbore: NO 25/11-G-11 BY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 3434.317
    mdTop: 3422.297
    wellbore: NO 25/11-G-11 BY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 3459.179
    mdTop: 3446.673
    wellbore: NO 25/11-G-11 BY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 3495.239
    mdTop: 3482.725
    wellbore: NO 25/11-G-11 BY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 3531.575
    mdTop: 3519.538
    wellbore: NO 25/11-G-11 BY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 3568.176
    mdTop: 3555.659
    wellbore: NO 25/11-G-11 BY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 3628.26
    mdTop: 3615.755
    wellbore: NO 25/11-G-11 BY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 3688.24
    mdTop: 3675.735
    wellbore: NO 25/11-G-11 BY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 3747.103
    mdTop: 3735.19
    wellbore: NO 25/11-G-11 BY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 3807.865
    mdTop: 3795.347
    wellbore: NO 25/11-G-11 BY1T4
