- wellbore:
   name: NO 25/11-G-32
   rms_name: 25_11-G-32
   short_name: G-32
   slot_name: NO 25/11-G-32
   field: Grane
   type: injection
   rkb: 69.9
   drilling_end_date: 2010-12-04T00:00:00
   fluids: water
- interval:
    equipment: Screen - generic
    mdBottom: 3368.639
    mdTop: 3240.101
    wellbore: NO 25/11-G-32
- interval:
    equipment: Screen - generic
    mdBottom: 3404.847
    mdTop: 3381.614
    wellbore: NO 25/11-G-32
