- wellbore:
   name: NO 25/11-G-16 Y2T2
   rms_name: 25_11-G-16_Y2T2
   short_name: G-16Y2T2
   slot_name: NO 25/11-G-16
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2008-10-05T00:00:00
   fluids: oil
- interval:
    equipment: Screen
    mdBottom: 3308.454
    mdTop: 3196.688
    wellbore: NO 25/11-G-16 Y2T2
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 3320.971
    mdTop: 3308.454
    wellbore: NO 25/11-G-16 Y2T2
- interval:
    equipment: Screen
    mdBottom: 4052.941
    mdTop: 3641.002
    wellbore: NO 25/11-G-16 Y2T2
- interval:
    equipment: Screen
    mdBottom: 4312.359
    mdTop: 4052.941
    wellbore: NO 25/11-G-16 Y2T2
- interval:
    equipment: Screen
    mdBottom: 4498.3
    mdTop: 4312.359
    wellbore: NO 25/11-G-16 Y2T2
