- wellbore:
   name: NO 25/11-G-5 BY1T2
   rms_name: 25_11-G-5_BY1T2
   short_name: G-5BY1T2
   slot_name: NO 25/11-G-5
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2011-11-09T00:00:00
   fluids: oil
- interval:
    equipment: Screen
    mdBottom: 2602.586
    mdTop: 2590.869
    wellbore: NO 25/11-G-5 BY1T2
- interval:
    equipment: Screen
    mdBottom: 2651.241
    mdTop: 2638.836
    wellbore: NO 25/11-G-5 BY1T2
- interval:
    equipment: Screen & Blank Pipe - generic
    mdBottom: 2990.714
    mdTop: 2734.908
    wellbore: NO 25/11-G-5 BY1T2
- interval:
    equipment: Screen & Blank Pipe - generic
    mdBottom: 3246.551
    mdTop: 2990.714
    wellbore: NO 25/11-G-5 BY1T2
- interval:
    equipment: Screen
    mdBottom: 3421.294
    mdTop: 3246.551
    wellbore: NO 25/11-G-5 BY1T2
- interval:
    equipment: Screen
    mdBottom: 3784.653
    mdTop: 3421.294
    wellbore: NO 25/11-G-5 BY1T2
