- wellbore:
   name: NO 25/11-G-26
   rms_name: 25_11-G-26
   short_name: G-26
   slot_name: NO 25/11-G-26
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2002-04-09T00:00:00
   fluids: oil
- interval:
    equipment: Screen
    mdBottom: 2331.760092
    mdTop: 2243.930092
    wellbore: NO 25/11-G-26
- interval:
    equipment: Screen
    mdBottom: 2500.720092
    mdTop: 2336.790092
    wellbore: NO 25/11-G-26
- interval:
    equipment: Screen
    mdBottom: 2552.450092
    mdTop: 2505.750092
    wellbore: NO 25/11-G-26
- interval:
    equipment: Screen
    mdBottom: 2763.900092
    mdTop: 2557.500092
    wellbore: NO 25/11-G-26
- interval:
    equipment: Screen
    mdBottom: 2840.420092
    mdTop: 2768.940092
    wellbore: NO 25/11-G-26
- interval:
    equipment: Screen
    mdBottom: 2939.900092
    mdTop: 2845.460092
    wellbore: NO 25/11-G-26
- interval:
    equipment: Screen
    mdBottom: 3197.720092
    mdTop: 2940.900092
    wellbore: NO 25/11-G-26
- interval:
    equipment: Screen
    mdBottom: 3238.880092
    mdTop: 3202.780092
    wellbore: NO 25/11-G-26
- interval:
    equipment: Screen
    mdBottom: 3280.500092
    mdTop: 3243.900092
    wellbore: NO 25/11-G-26
- interval:
    equipment: Screen
    mdBottom: 3357.710092
    mdTop: 3285.600092
    wellbore: NO 25/11-G-26
- interval:
    equipment: Screen
    mdBottom: 3446.950092
    mdTop: 3362.780092
    wellbore: NO 25/11-G-26
- interval:
    equipment: Screen
    mdBottom: 3583.290092
    mdTop: 3447.950092
    wellbore: NO 25/11-G-26
- interval:
    equipment: Screen
    mdBottom: 2231.86
    mdTop: 2206.7
    wellbore: NO 25/11-G-26
