- wellbore:
   name: NO 25/11-G-10 Y1
   rms_name: 25_11-G-10_Y1
   short_name: G-10Y1
   slot_name: NO 25/11-G-10
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2006-01-11T00:00:00
   fluids: oil
- interval:
    equipment: Screen - generic
    mdBottom: 4117.065
    mdTop: 4082.033
    wellbore: NO 25/11-G-10 Y1
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 4128.726
    mdTop: 4117.065
    wellbore: NO 25/11-G-10 Y1
- interval:
    equipment: Screen - generic
    mdBottom: 4163.752
    mdTop: 4128.726
    wellbore: NO 25/11-G-10 Y1
- interval:
    equipment: Screen & Blank Pipe - generic
    mdBottom: 4248.301
    mdTop: 4166.792
    wellbore: NO 25/11-G-10 Y1
- interval:
    equipment: Screen - generic
    mdBottom: 4283.43
    mdTop: 4248.301
    wellbore: NO 25/11-G-10 Y1
- interval:
    equipment: Screen & Blank Pipe - generic
    mdBottom: 2469.924
    mdTop: 2326.641
    wellbore: NO 25/11-G-10 Y1
- interval:
    equipment: Screen & Blank Pipe - generic
    mdBottom: 2539.381
    mdTop: 2469.924
    wellbore: NO 25/11-G-10 Y1
- interval:
    equipment: Screen - generic
    mdBottom: 2841.514
    mdTop: 2539.381
    wellbore: NO 25/11-G-10 Y1
- interval:
    equipment: Screen - generic
    mdBottom: 3296.507
    mdTop: 2841.514
    wellbore: NO 25/11-G-10 Y1
- interval:
    equipment: Screen - generic
    mdBottom: 3386.214
    mdTop: 3316.147
    wellbore: NO 25/11-G-10 Y1
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 3397.89
    mdTop: 3386.214
    wellbore: NO 25/11-G-10 Y1
- interval:
    equipment: Screen - generic
    mdBottom: 3455.696
    mdTop: 3397.89
    wellbore: NO 25/11-G-10 Y1
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 3467.375
    mdTop: 3455.696
    wellbore: NO 25/11-G-10 Y1
- interval:
    equipment: Screen - generic
    mdBottom: 3502.392
    mdTop: 3467.375
    wellbore: NO 25/11-G-10 Y1
- interval:
    equipment: Screen - generic
    mdBottom: 4062.303
    mdTop: 3502.392
    wellbore: NO 25/11-G-10 Y1
