- wellbore:
   name: NO 25/11-G-5 AT2
   rms_name: 25_11-G-5_AT2
   short_name: G-5AT2
   slot_name: NO 25/11-G-5
   field: Grane
   type: observation
   rkb: 69.9
   drilling_end_date: 2011-08-09T00:00:00
   fluids: oil
