- wellbore:
   name: NO 25/11-G-11 BY3T2
   rms_name: 25_11-G-11_BY3T2
   short_name: G-11BY3T2
   slot_name: NO 25/11-G-11
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2013-07-21T00:00:00
   fluids: oil
- interval:
    equipment: Screen - generic
    mdBottom: 3692.229
    mdTop: 3679.705
    wellbore: NO 25/11-G-11 BY3T2
- interval:
    equipment: Screen - generic
    mdBottom: 3728.813
    mdTop: 3716.307
    wellbore: NO 25/11-G-11 BY3T2
- interval:
    equipment: Screen - generic
    mdBottom: 3838.196
    mdTop: 3751.849
    wellbore: NO 25/11-G-11 BY3T2
- interval:
    equipment: Screen - generic
    mdBottom: 3850.54
    mdTop: 3838.196
    wellbore: NO 25/11-G-11 BY3T2
- interval:
    equipment: Screen - generic
    mdBottom: 3862.899
    mdTop: 3850.54
    wellbore: NO 25/11-G-11 BY3T2
- interval:
    equipment: Screen - generic
    mdBottom: 3887.409
    mdTop: 3874.887
    wellbore: NO 25/11-G-11 BY3T2
- interval:
    equipment: Screen - generic
    mdBottom: 3910.393
    mdTop: 3898.35
    wellbore: NO 25/11-G-11 BY3T2
- interval:
    equipment: Screen - generic
    mdBottom: 3934.421
    mdTop: 3922.38
    wellbore: NO 25/11-G-11 BY3T2
- interval:
    equipment: Screen - generic
    mdBottom: 3957.84
    mdTop: 3945.932
    wellbore: NO 25/11-G-11 BY3T2
- interval:
    equipment: Screen - generic
    mdBottom: 3982.241
    mdTop: 3969.727
    wellbore: NO 25/11-G-11 BY3T2
- interval:
    equipment: Screen - generic
    mdBottom: 4006.107
    mdTop: 3993.752
    wellbore: NO 25/11-G-11 BY3T2
- interval:
    equipment: Screen - generic
    mdBottom: 4030.261
    mdTop: 4017.903
    wellbore: NO 25/11-G-11 BY3T2
- interval:
    equipment: Screen - generic
    mdBottom: 4164.561
    mdTop: 4030.261
    wellbore: NO 25/11-G-11 BY3T2
- interval:
    equipment: Screen - generic
    mdBottom: 4201.485
    mdTop: 4164.561
    wellbore: NO 25/11-G-11 BY3T2
