- wellbore:
   name: NO 25/11-G-6 AY1T3
   rms_name: 25_11-G-6_AY1T3
   short_name: G-6AY1T3
   slot_name: NO 25/11-G-6
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2016-08-24T00:00:00
   fluids: oil
- interval:
    equipment: Screen - generic
    mdBottom: 3032.739
    mdTop: 3021.282
    wellbore: NO 25/11-G-6 AY1T3
- interval:
    equipment: Screen - generic
    mdBottom: 3057.086
    mdTop: 3044.744
    wellbore: NO 25/11-G-6 AY1T3
- interval:
    equipment: Screen - generic
    mdBottom: 3081.445
    mdTop: 3069.095
    wellbore: NO 25/11-G-6 AY1T3
- interval:
    equipment: Screen - generic
    mdBottom: 3104.649
    mdTop: 3093.452
    wellbore: NO 25/11-G-6 AY1T3
- interval:
    equipment: Screen - generic
    mdBottom: 3128.146
    mdTop: 3116.655
    wellbore: NO 25/11-G-6 AY1T3
- interval:
    equipment: Screen - generic
    mdBottom: 3151.992
    mdTop: 3140.15
    wellbore: NO 25/11-G-6 AY1T3
- interval:
    equipment: Screen - generic
    mdBottom: 3175.809
    mdTop: 3163.997
    wellbore: NO 25/11-G-6 AY1T3
- interval:
    equipment: Screen - generic
    mdBottom: 3200.157
    mdTop: 3187.816
    wellbore: NO 25/11-G-6 AY1T3
- interval:
    equipment: Screen - generic
    mdBottom: 3224.509
    mdTop: 3212.168
    wellbore: NO 25/11-G-6 AY1T3
- interval:
    equipment: Screen - generic
    mdBottom: 3248.531
    mdTop: 3236.38
    wellbore: NO 25/11-G-6 AY1T3
- interval:
    equipment: Screen - generic
    mdBottom: 3272.769
    mdTop: 3260.551
    wellbore: NO 25/11-G-6 AY1T3
- interval:
    equipment: Screen - generic
    mdBottom: 3297.124
    mdTop: 3284.782
    wellbore: NO 25/11-G-6 AY1T3
- interval:
    equipment: Screen - generic
    mdBottom: 3321.191
    mdTop: 3309.14
    wellbore: NO 25/11-G-6 AY1T3
- interval:
    equipment: Screen - generic
    mdBottom: 3345.544
    mdTop: 3333.189
    wellbore: NO 25/11-G-6 AY1T3
- interval:
    equipment: Screen - generic
    mdBottom: 3369.575
    mdTop: 3357.542
    wellbore: NO 25/11-G-6 AY1T3
- interval:
    equipment: Screen - generic
    mdBottom: 3393.614
    mdTop: 3381.578
    wellbore: NO 25/11-G-6 AY1T3
- interval:
    equipment: Screen - generic
    mdBottom: 3417.156
    mdTop: 3405.101
    wellbore: NO 25/11-G-6 AY1T3
- interval:
    equipment: Screen - generic
    mdBottom: 3441.509
    mdTop: 3429.166
    wellbore: NO 25/11-G-6 AY1T3
- interval:
    equipment: Screen - generic
    mdBottom: 3465.86
    mdTop: 3453.517
    wellbore: NO 25/11-G-6 AY1T3
- interval:
    equipment: Screen - generic
    mdBottom: 3489.909
    mdTop: 3477.868
    wellbore: NO 25/11-G-6 AY1T3
- interval:
    equipment: Screen - generic
    mdBottom: 3514.26
    mdTop: 3501.92
    wellbore: NO 25/11-G-6 AY1T3
- interval:
    equipment: Screen - generic
    mdBottom: 3537.763
    mdTop: 3525.754
    wellbore: NO 25/11-G-6 AY1T3
- interval:
    equipment: Screen - generic
    mdBottom: 3561.804
    mdTop: 3549.778
    wellbore: NO 25/11-G-6 AY1T3
- interval:
    equipment: Screen - generic
    mdBottom: 3586.162
    mdTop: 3573.822
    wellbore: NO 25/11-G-6 AY1T3
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 3598.666
    mdTop: 3586.162
    wellbore: NO 25/11-G-6 AY1T3
- interval:
    equipment: Screen - generic
    mdBottom: 4239.472
    mdTop: 3598.666
    wellbore: NO 25/11-G-6 AY1T3
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 4251.905
    mdTop: 4239.472
    wellbore: NO 25/11-G-6 AY1T3
- interval:
    equipment: Screen - generic
    mdBottom: 2985.251
    mdTop: 2678.57
    wellbore: NO 25/11-G-6 AY1T3
- interval:
    equipment: Screen - generic
    mdBottom: 3009.279
    mdTop: 2997.258
    wellbore: NO 25/11-G-6 AY1T3
