- wellbore:
   name: NO 25/11-G-5 BY3
   rms_name: 25_11-G-5_BY3
   short_name: G-5BY3
   slot_name: NO 25/11-G-5
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2011-12-09T00:00:00
   fluids: oil
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 2360.374
    mdTop: 2348.32
    wellbore: NO 25/11-G-5 BY3
- interval:
    equipment: Screen & Blank Pipe - generic
    mdBottom: 3086.3
    mdTop: 2360.374
    wellbore: NO 25/11-G-5 BY3
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 3098.319
    mdTop: 3086.3
    wellbore: NO 25/11-G-5 BY3
- interval:
    equipment: Screen
    mdBottom: 3658.178
    mdTop: 3098.319
    wellbore: NO 25/11-G-5 BY3
- interval:
    equipment: Screen
    mdBottom: 3863.321
    mdTop: 3706.248
    wellbore: NO 25/11-G-5 BY3
