- wellbore:
   name: NO 25/11-G-8
   rms_name: 25_11-G-8
   short_name: G-8
   slot_name: NO 25/11-G-8
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2005-11-20T00:00:00
   fluids: oil
