- wellbore:
   name: NO 25/11-G-15
   rms_name: 25_11-G-15
   short_name: G-15
   slot_name: NO 25/11-G-15
   field: Grane
   type: observation
   rkb: 69.9
   drilling_end_date: 2008-12-13T00:00:00
   fluids: oil
