- wellbore:
   name: NO 25/11-G-20 A
   rms_name: 25_11-G-20_A
   short_name: G-20A
   slot_name: NO 25/11-G-20
   field: Grane
   type: injection
   rkb: 69.9
   drilling_end_date: 2002-05-26T00:00:00
   fluids: gas
