- wellbore:
   name: NO 25/11-G-21 BY1
   rms_name: 25_11-G-21_BY1
   short_name: G-21BY1
   slot_name: NO 25/11-G-21
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2012-05-15T00:00:00
   fluids: oil
