- wellbore:
   name: NO 25/11-G-2 BY3
   rms_name: 25_11-G-2_BY3
   short_name: G-2BY3
   slot_name: NO 25/11-G-2
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2015-04-29T00:00:00
   fluids: oil
- interval:
    equipment: Screen
    mdBottom: 4500.319
    mdTop: 4239.653
    wellbore: NO 25/11-G-2 BY3
