- wellbore:
   name: NO 25/11-G-6
   rms_name: 25_11-G-6
   short_name: G-6
   slot_name: NO 25/11-G-6
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2004-08-12T00:00:00
   fluids: oil
- interval:
    equipment: Screen
    mdBottom: 3162.968
    mdTop: 2194.979
    wellbore: NO 25/11-G-6
- interval:
    equipment: Screen
    mdBottom: 4313.309
    mdTop: 3170.167
    wellbore: NO 25/11-G-6
