- wellbore:
   name: NO 25/11-G-1 Y1
   rms_name: 25_11-G-1_Y1
   short_name: G-1Y1
   slot_name: NO 25/11-G-1
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2008-02-12T00:00:00
   fluids: oil
- interval:
    equipment: Screen - generic
    mdBottom: 3905.45
    mdTop: 3731.335
    wellbore: NO 25/11-G-1 Y1
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 3917.973
    mdTop: 3905.45
    wellbore: NO 25/11-G-1 Y1
- interval:
    equipment: Screen - generic
    mdBottom: 4240.67
    mdTop: 3917.973
    wellbore: NO 25/11-G-1 Y1
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 4253.051
    mdTop: 4240.67
    wellbore: NO 25/11-G-1 Y1
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 4265.567
    mdTop: 4253.051
    wellbore: NO 25/11-G-1 Y1
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 4278.074
    mdTop: 4265.567
    wellbore: NO 25/11-G-1 Y1
