- wellbore:
   name: NO 25/11-G-39 CY1T2
   rms_name: 25_11-G-39_CY1T2
   short_name: G-39CY1T2
   slot_name: NO 25/11-G-39
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2018-03-25T00:00:00
   fluids: oil
- interval:
    equipment: Screen - generic
    mdBottom: 4871.939
    mdTop: 4404.875
    wellbore: NO 25/11-G-39 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 4883.952
    mdTop: 4871.939
    wellbore: NO 25/11-G-39 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 5003.391
    mdTop: 4883.952
    wellbore: NO 25/11-G-39 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 5014.819
    mdTop: 5003.391
    wellbore: NO 25/11-G-39 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 5038.865
    mdTop: 5014.819
    wellbore: NO 25/11-G-39 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 5050.876
    mdTop: 5038.865
    wellbore: NO 25/11-G-39 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 5350.719
    mdTop: 5050.876
    wellbore: NO 25/11-G-39 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 5362.73
    mdTop: 5350.719
    wellbore: NO 25/11-G-39 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 5698.845
    mdTop: 5362.73
    wellbore: NO 25/11-G-39 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 5710.852
    mdTop: 5698.845
    wellbore: NO 25/11-G-39 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 6106.882
    mdTop: 5710.852
    wellbore: NO 25/11-G-39 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 6118.397
    mdTop: 6106.882
    wellbore: NO 25/11-G-39 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 6395.481
    mdTop: 6118.397
    wellbore: NO 25/11-G-39 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 6407.176
    mdTop: 6395.481
    wellbore: NO 25/11-G-39 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 6610.253
    mdTop: 6407.176
    wellbore: NO 25/11-G-39 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 6622.186
    mdTop: 6610.253
    wellbore: NO 25/11-G-39 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 6742.377
    mdTop: 6622.186
    wellbore: NO 25/11-G-39 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 6754.392
    mdTop: 6742.377
    wellbore: NO 25/11-G-39 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 6924.696
    mdTop: 6754.392
    wellbore: NO 25/11-G-39 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 6936.429
    mdTop: 6924.696
    wellbore: NO 25/11-G-39 CY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 6984.416
    mdTop: 6936.429
    wellbore: NO 25/11-G-39 CY1T2
