- wellbore:
   name: NO 25/11-G-13 Y1T3
   rms_name: 25_11-G-13_Y1T3
   short_name: G-13Y1T3
   slot_name: NO 25/11-G-13
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2009-05-16T00:00:00
   fluids: oil
- interval:
    equipment: Screen
    mdBottom: 5416.924
    mdTop: 5029.034
    wellbore: NO 25/11-G-13 Y1T3
- interval:
    equipment: Screen
    mdBottom: 6110.234
    mdTop: 5416.924
    wellbore: NO 25/11-G-13 Y1T3
- interval:
    equipment: Screen
    mdBottom: 6469.234
    mdTop: 6110.234
    wellbore: NO 25/11-G-13 Y1T3
