- wellbore:
   name: NO 25/11-G-5 BY4T3
   rms_name: 25_11-G-5_BY4T3
   short_name: G-5BY4T3
   slot_name: NO 25/11-G-5
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2011-12-29T00:00:00
   fluids: oil
- interval:
    equipment: Screen
    mdBottom: 2415.592
    mdTop: 2403.072
    wellbore: NO 25/11-G-5 BY4T3
- interval:
    equipment: Screen
    mdBottom: 2464.268
    mdTop: 2451.757
    wellbore: NO 25/11-G-5 BY4T3
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 2512.805
    mdTop: 2500.415
    wellbore: NO 25/11-G-5 BY4T3
- interval:
    equipment: Screen
    mdBottom: 2537.503
    mdTop: 2512.805
    wellbore: NO 25/11-G-5 BY4T3
- interval:
    equipment: Screen
    mdBottom: 2851.26
    mdTop: 2537.503
    wellbore: NO 25/11-G-5 BY4T3
- interval:
    equipment: Screen & Blank Pipe - generic
    mdBottom: 2354.888
    mdTop: 2184.763
    wellbore: NO 25/11-G-5 BY4T3
