- wellbore:
   name: NO 25/11-G-22 AT2
   rms_name: 25_11-G-22_AT2
   short_name: G-22AT2
   slot_name: NO 25/11-G-22
   field: Grane
   type: observation
   rkb: 69.9
   drilling_end_date: 2016-02-19T00:00:00
   fluids: oil
