- wellbore:
   name: NO 25/11-G-27 A
   rms_name: 25_11-G-27_A
   short_name: G-27A
   slot_name: NO 25/11-G-27
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2002-12-09T00:00:00
   fluids: oil
- interval:
    equipment: Screen
    mdBottom: 2122.47
    mdTop: 1908.86
    wellbore: NO 25/11-G-27 A
- interval:
    equipment: Screen
    mdBottom: 2383.3
    mdTop: 2134.44
    wellbore: NO 25/11-G-27 A
- interval:
    equipment: Screen
    mdBottom: 2643.71
    mdTop: 2395.2
    wellbore: NO 25/11-G-27 A
- interval:
    equipment: Screen
    mdBottom: 2822.83
    mdTop: 2655.62
    wellbore: NO 25/11-G-27 A
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 2834.36
    mdTop: 2822.83
    wellbore: NO 25/11-G-27 A
- interval:
    equipment: Screen
    mdBottom: 2986.08
    mdTop: 2856.58
    wellbore: NO 25/11-G-27 A
- interval:
    equipment: Screen
    mdBottom: 3044.3
    mdTop: 2986.93
    wellbore: NO 25/11-G-27 A
- interval:
    equipment: Screen
    mdBottom: 3220.04
    mdTop: 3056.2
    wellbore: NO 25/11-G-27 A
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 3231.94
    mdTop: 3220.04
    wellbore: NO 25/11-G-27 A
- interval:
    equipment: Screen
    mdBottom: 3279.04
    mdTop: 3243.82
    wellbore: NO 25/11-G-27 A
- interval:
    equipment: Screen
    mdBottom: 3433.04
    mdTop: 3279.89
    wellbore: NO 25/11-G-27 A
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 3444.77
    mdTop: 3433.04
    wellbore: NO 25/11-G-27 A
