- wellbore:
   name: NO 25/11-15
   rms_name: 25_11-15
   short_name: 15
   slot_name: NO 25/11-15
   field: Grane
   type: wildcat
   rkb: 23.5
   drilling_end_date: 1991-12-25T00:00:00
   fluids: oil
