- wellbore:
   name: NO 25/11-G-11 CT2
   rms_name: 25_11-G-11_CT2
   short_name: G-11CT2
   slot_name: NO 25/11-G-11
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2013-06-19T00:00:00
   fluids: oil
