- wellbore:
   name: NO 25/11-G-1 Y4T2
   rms_name: 25_11-G-1_Y4T2
   short_name: G-1Y4T2
   slot_name: NO 25/11-G-1
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2008-04-23T00:00:00
   fluids: oil
- interval:
    equipment: Screen - generic
    mdBottom: 3673.804
    mdTop: 3600.068
    wellbore: NO 25/11-G-1 Y4T2
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 3686.313
    mdTop: 3673.804
    wellbore: NO 25/11-G-1 Y4T2
- interval:
    equipment: Screen - generic
    mdBottom: 3723.734
    mdTop: 3686.313
    wellbore: NO 25/11-G-1 Y4T2
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 3735.252
    mdTop: 3723.734
    wellbore: NO 25/11-G-1 Y4T2
- interval:
    equipment: Screen - generic
    mdBottom: 3796.755
    mdTop: 3735.252
    wellbore: NO 25/11-G-1 Y4T2
- interval:
    equipment: Screen - generic
    mdBottom: 4748.988
    mdTop: 4325.681
    wellbore: NO 25/11-G-1 Y4T2
