- wellbore:
   name: NO 25/11-G-7 B
   rms_name: 25_11-G-7_B
   short_name: G-7B
   slot_name: NO 25/11-G-7
   field: Grane
   type: observation
   rkb: 69.9
   drilling_end_date: 
   fluids: not applicable
