- wellbore:
   name: NO 25/11-G-2 Y2
   rms_name: 25_11-G-2_Y2
   short_name: G-2Y2
   slot_name: NO 25/11-G-2
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2007-05-06T00:00:00
   fluids: oil
