- wellbore:
   name: NO 25/11-G-12 AY1
   rms_name: 25_11-G-12_AY1
   short_name: G-12AY1
   slot_name: NO 25/11-G-12
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2016-11-22T00:00:00
   fluids: oil
