- wellbore:
   name: NO 25/11-G-10 AY1
   rms_name: 25_11-G-10_AY1
   short_name: G-10AY1
   slot_name: NO 25/11-G-10
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 
   fluids: oil
