- wellbore:
   name: NO 25/11-G-17 AT2
   rms_name: 25_11-G-17_AT2
   short_name: G-17AT2
   slot_name: NO 25/11-G-17
   field: Grane
   type: observation
   rkb: 69.9
   drilling_end_date: 2012-09-02T00:00:00
   fluids: oil
