- wellbore:
   name: NO 25/11-G-19 AT2
   rms_name: 25_11-G-19_AT2
   short_name: G-19AT2
   slot_name: NO 25/11-G-19
   field: Grane
   type: observation
   rkb: 69.9
   drilling_end_date: 2014-07-09T00:00:00
   fluids: oil
