- wellbore:
   name: NO 25/11-G-31 AY1
   rms_name: 25_11-G-31_AY1
   short_name: G-31AY1
   slot_name: NO 25/11-G-31
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2015-10-02T00:00:00
   fluids: oil
