- wellbore:
   name: NO 25/11-21 AT2
   rms_name: 25_11-21_AT2
   short_name: 21AT2
   slot_name: NO 25/11-21
   field: Grane
   type: appraisal
   rkb: 26
   drilling_end_date: 1996-10-01T00:00:00
   fluids: oil
