- wellbore:
   name: NO 25/11-G-39 AY1T2
   rms_name: 25_11-G-39_AY1T2
   short_name: G-39AY1T2
   slot_name: NO 25/11-G-39
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2007-06-17T00:00:00
   fluids: not applicable
