- wellbore:
   name: NO 25/11-G-39 BY3
   rms_name: 25_11-G-39_BY3
   short_name: G-39BY3
   slot_name: NO 25/11-G-39
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2007-11-08T00:00:00
   fluids: oil
- interval:
    equipment: Screen - generic
    mdBottom: 4865.191
    mdTop: 4468.714
    wellbore: NO 25/11-G-39 BY3
- interval:
    equipment: Screen - generic
    mdBottom: 4970.205
    mdTop: 4871.041
    wellbore: NO 25/11-G-39 BY3
- interval:
    equipment: Screen - generic
    mdBottom: 5169.229
    mdTop: 4970.205
    wellbore: NO 25/11-G-39 BY3
- interval:
    equipment: Screen - generic
    mdBottom: 5393.738
    mdTop: 5169.229
    wellbore: NO 25/11-G-39 BY3
