- wellbore:
   name: NO 25/11-G-12 Y1T3
   rms_name: 25_11-G-12_Y1T3
   short_name: G-12Y1T3
   slot_name: NO 25/11-G-12
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2006-10-21T00:00:00
   fluids: oil
- interval:
    equipment: Screen & Blank Pipe
    mdBottom: 3410.585
    mdTop: 3287.038
    wellbore: NO 25/11-G-12 Y1T3
- interval:
    equipment: Screen & Blank Pipe - generic
    mdBottom: 3797.001
    mdTop: 3410.585
    wellbore: NO 25/11-G-12 Y1T3
- interval:
    equipment: Screen & Blank Pipe - generic
    mdBottom: 4231.127
    mdTop: 3797.001
    wellbore: NO 25/11-G-12 Y1T3
