- wellbore:
   name: NO 25/11-G-25 AY3
   rms_name: 25_11-G-25_AY3
   short_name: G-25AY3
   slot_name: NO 25/11-G-25
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2015-12-12T00:00:00
   fluids: oil
- interval:
    equipment: Screen & Blank Pipe - generic
    mdBottom: 3155.296
    mdTop: 2381.275
    wellbore: NO 25/11-G-25 AY3
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 3167.645
    mdTop: 3155.296
    wellbore: NO 25/11-G-25 AY3
- interval:
    equipment: Screen & Blank Pipe - generic
    mdBottom: 3836.211
    mdTop: 3787.593
    wellbore: NO 25/11-G-25 AY3
- interval:
    equipment: Screen - generic
    mdBottom: 4427.723
    mdTop: 3836.211
    wellbore: NO 25/11-G-25 AY3
