- wellbore:
   name: NO 25/11-G-9 AY1
   rms_name: 25_11-G-9_AY1
   short_name: G-9AY1
   slot_name: NO 25/11-G-9
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2018-07-04T00:00:00
   fluids: 
