- wellbore:
   name: NO 25/11-G-2 Y1
   rms_name: 25_11-G-2_Y1
   short_name: G-2Y1
   slot_name: NO 25/11-G-2
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2007-04-12T00:00:00
   fluids: oil
- interval:
    equipment: Screen
    mdBottom: 5013.723
    mdTop: 4414.907
    wellbore: NO 25/11-G-2 Y1
