- wellbore:
   name: NO 25/11-G-28
   rms_name: 25_11-G-28
   short_name: G-28
   slot_name: NO 25/11-G-28
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2002-10-22T00:00:00
   fluids: oil
- interval:
    equipment: Screen
    mdBottom: 3659.84
    mdTop: 3446.95
    wellbore: NO 25/11-G-28
- interval:
    equipment: Screen
    mdBottom: 3789.02
    mdTop: 3671.84
    wellbore: NO 25/11-G-28
- interval:
    equipment: Screen
    mdBottom: 3955.32
    mdTop: 3801.01
    wellbore: NO 25/11-G-28
- interval:
    equipment: Screen
    mdBottom: 4132.47
    mdTop: 3967.3
    wellbore: NO 25/11-G-28
- interval:
    equipment: Screen
    mdBottom: 4216.23
    mdTop: 4133.46
    wellbore: NO 25/11-G-28
- interval:
    equipment: Screen
    mdBottom: 4404.93
    mdTop: 4228.23
    wellbore: NO 25/11-G-28
- interval:
    equipment: Screen
    mdBottom: 4499.44
    mdTop: 4416.43
    wellbore: NO 25/11-G-28
- interval:
    equipment: Screen
    mdBottom: 4571.17
    mdTop: 4500.3
    wellbore: NO 25/11-G-28
- interval:
    equipment: Screen
    mdBottom: 4549.755
    mdTop: 4537.655
    wellbore: NO 25/11-G-28
- interval:
    equipment: Screen
    mdBottom: 4537.655
    mdTop: 3118.365
    wellbore: NO 25/11-G-28
- interval:
    equipment: Screen
    mdBottom: 3151.46
    mdTop: 3127.69
    wellbore: NO 25/11-G-28
- interval:
    equipment: Screen
    mdBottom: 3434.97
    mdTop: 3163.44
    wellbore: NO 25/11-G-28
