- wellbore:
   name: NO 25/11-G-16 AY1
   rms_name: 25_11-G-16_AY1
   short_name: G-16AY1
   slot_name: NO 25/11-G-16
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2017-08-10T00:00:00
   fluids: oil
