- wellbore:
   name: NO 25/11-G-14
   rms_name: 25_11-G-14
   short_name: G-14
   slot_name: NO 25/11-G-14
   field: Grane
   type: injection
   rkb: 69.9
   drilling_end_date: 2004-03-18T00:00:00
   fluids: water
- interval:
    equipment: Screen
    mdBottom: 1189.054
    mdTop: 1177.036
    wellbore: NO 25/11-G-14
- interval:
    equipment: Screen
    mdBottom: 993.423
    mdTop: 980.914
    wellbore: NO 25/11-G-14
- interval:
    equipment: Screen
    mdBottom: 1177.036
    mdTop: 993.338
    wellbore: NO 25/11-G-14
- interval:
    equipment: Screen
    mdBottom: 1491.652
    mdTop: 1167.249
    wellbore: NO 25/11-G-14
