- wellbore:
   name: NO 25/11-G-5 CY4T2
   rms_name: 25_11-G-5_CY4T2
   short_name: G-5CY4T2
   slot_name: NO 25/11-G-5
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2019-04-22T00:00:00
   fluids: 
