- wellbore:
   name: NO 25/11-G-16 Y3T2
   rms_name: 25_11-G-16_Y3T2
   short_name: G-16Y3T2
   slot_name: NO 25/11-G-16
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2009-08-04T00:00:00
   fluids: oil
- interval:
    equipment: Screen
    mdBottom: 4152.601
    mdTop: 3207.863
    wellbore: NO 25/11-G-16 Y3T2
- interval:
    equipment: Screen
    mdBottom: 4547.19
    mdTop: 4152.601
    wellbore: NO 25/11-G-16 Y3T2
