- wellbore:
   name: NO 25/11-G-24
   rms_name: 25_11-G-24
   short_name: G-24
   slot_name: NO 25/11-G-24
   field: Grane
   type: observation
   rkb: 69.9
   drilling_end_date: 2001-10-15T00:00:00
   fluids: not applicable
