- wellbore:
   name: NO 25/11-G-2 Y3
   rms_name: 25_11-G-2_Y3
   short_name: G-2Y3
   slot_name: NO 25/11-G-2
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2007-07-15T00:00:00
   fluids: oil
