- wellbore:
   name: NO 25/11-G-17 A
   rms_name: 25_11-G-17_A
   short_name: G-17A
   slot_name: NO 25/11-G-17
   field: Grane
   type: observation
   rkb: 69.9
   drilling_end_date: 2012-08-31T00:00:00
   fluids: oil
