- wellbore:
   name: NO 25/11-G-21 BY2T2
   rms_name: 25_11-G-21_BY2T2
   short_name: G-21BY2T2
   slot_name: NO 25/11-G-21
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2012-06-21T00:00:00
   fluids: oil
- interval:
    equipment: Screen - generic
    mdBottom: 3505.028
    mdTop: 3395.86
    wellbore: NO 25/11-G-21 BY2T2
- interval:
    equipment: Screen - generic
    mdBottom: 3998.604
    mdTop: 3505.028
    wellbore: NO 25/11-G-21 BY2T2
