- wellbore:
   name: NO 25/11-G-4 T2
   rms_name: 25_11-G-4_T2
   short_name: G-4T2
   slot_name: NO 25/11-G-4
   field: Grane
   type: injection
   rkb: 69.9
   drilling_end_date: 2010-04-28T00:00:00
   fluids: gas
- interval:
    equipment: Screen - generic
    mdBottom: 6424.907
    mdTop: 6299.857
    wellbore: NO 25/11-G-4 T2
