- wellbore:
   name: NO 25/11-G-25 AY1
   rms_name: 25_11-G-25_AY1
   short_name: G-25AY1
   slot_name: NO 25/11-G-25
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2015-11-21T00:00:00
   fluids: oil
