- wellbore:
   name: NO 25/11-G-5 A
   rms_name: 25_11-G-5_A
   short_name: G-5A
   slot_name: NO 25/11-G-5
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2011-10-18T00:00:00
   fluids: not applicable
