- wellbore:
   name: NO 25/11-G-40 BY2
   rms_name: 25_11-G-40_BY2
   short_name: G-40BY2
   slot_name: NO 25/11-G-40
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 
   fluids: 
