- wellbore:
   name: NO 25/11-G-9
   rms_name: 25_11-G-9
   short_name: G-9
   slot_name: NO 25/11-G-9
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2004-05-18T00:00:00
   fluids: oil
- interval:
    equipment: Screen
    mdBottom: 3428.414
    mdTop: 2234.13
    wellbore: NO 25/11-G-9
