- wellbore:
   name: NO 25/11-G-34 AY4
   rms_name: 25_11-G-34_AY4
   short_name: G-34AY4
   slot_name: NO 25/11-G-34
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2019-01-14T00:00:00
   fluids: oil
- interval:
    equipment: Screen - generic
    mdBottom: 3198.577
    mdTop: 3186.7980000000002
    wellbore: NO 25/11-G-34 AY4
- interval:
    equipment: Screen - generic
    mdBottom: 3234.0310000000004
    mdTop: 3210.5800000000004
    wellbore: NO 25/11-G-34 AY4
- interval:
    equipment: Screen - generic
    mdBottom: 3269.4130000000005
    mdTop: 3245.983
    wellbore: NO 25/11-G-34 AY4
- interval:
    equipment: Screen - generic
    mdBottom: 3304.7630000000004
    mdTop: 3281.327
    wellbore: NO 25/11-G-34 AY4
- interval:
    equipment: Screen - generic
    mdBottom: 3351.981
    mdTop: 3316.708
    wellbore: NO 25/11-G-34 AY4
- interval:
    equipment: Screen - generic
    mdBottom: 2666.9120000000003
    mdTop: 2643.485
    wellbore: NO 25/11-G-34 AY4
- interval:
    equipment: Screen - generic
    mdBottom: 2702.4370000000004
    mdTop: 2678.8750000000005
    wellbore: NO 25/11-G-34 AY4
- interval:
    equipment: Screen - generic
    mdBottom: 2737.8170000000005
    mdTop: 2714.3970000000004
    wellbore: NO 25/11-G-34 AY4
- interval:
    equipment: Screen - generic
    mdBottom: 2773.28
    mdTop: 2749.7900000000004
    wellbore: NO 25/11-G-34 AY4
- interval:
    equipment: Screen - generic
    mdBottom: 2808.755
    mdTop: 2785.2360000000003
    wellbore: NO 25/11-G-34 AY4
- interval:
    equipment: Screen - generic
    mdBottom: 2844.226
    mdTop: 2820.7230000000004
    wellbore: NO 25/11-G-34 AY4
- interval:
    equipment: Screen - generic
    mdBottom: 2879.686
    mdTop: 2856.186
    wellbore: NO 25/11-G-34 AY4
- interval:
    equipment: Screen - generic
    mdBottom: 2915.1820000000002
    mdTop: 2891.684
    wellbore: NO 25/11-G-34 AY4
- interval:
    equipment: Screen - generic
    mdBottom: 2950.456
    mdTop: 2927.005
    wellbore: NO 25/11-G-34 AY4
- interval:
    equipment: Screen - generic
    mdBottom: 2985.9010000000003
    mdTop: 2962.4120000000003
    wellbore: NO 25/11-G-34 AY4
- interval:
    equipment: Screen - generic
    mdBottom: 3021.166
    mdTop: 2997.7250000000004
    wellbore: NO 25/11-G-34 AY4
- interval:
    equipment: Screen - generic
    mdBottom: 3056.6220000000003
    mdTop: 3033.1200000000003
    wellbore: NO 25/11-G-34 AY4
- interval:
    equipment: Screen - generic
    mdBottom: 3091.9800000000005
    mdTop: 3068.5910000000003
    wellbore: NO 25/11-G-34 AY4
- interval:
    equipment: Screen - generic
    mdBottom: 3127.4860000000003
    mdTop: 3103.943
    wellbore: NO 25/11-G-34 AY4
- interval:
    equipment: Screen - generic
    mdBottom: 3163.065
    mdTop: 3139.478
    wellbore: NO 25/11-G-34 AY4
- interval:
    equipment: Screen - generic
    mdBottom: 3186.7980000000002
    mdTop: 3175.0220000000004
    wellbore: NO 25/11-G-34 AY4
