- wellbore:
   name: NO 25/11-18 T2
   rms_name: 25_11-18_T2
   short_name: 18T2
   slot_name: NO 25/11-18
   field: Grane
   type: appraisal
   rkb: 22
   drilling_end_date: 1994-10-21T00:00:00
   fluids: oil
