- wellbore:
   name: NO 25/11-G-12 AY2
   rms_name: 25_11-G-12_AY2
   short_name: G-12AY2
   slot_name: NO 25/11-G-12
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2016-11-30T00:00:00
   fluids: oil
- interval:
    equipment: Screen - generic
    mdBottom: 3519.819
    mdTop: 3507.685
    wellbore: NO 25/11-G-12 AY2
- interval:
    equipment: Screen - generic
    mdBottom: 3556.208
    mdTop: 3543.826
    wellbore: NO 25/11-G-12 AY2
- interval:
    equipment: Screen - generic
    mdBottom: 4105.175
    mdTop: 3748.462
    wellbore: NO 25/11-G-12 AY2
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 4117.558
    mdTop: 4105.175
    wellbore: NO 25/11-G-12 AY2
- interval:
    equipment: Screen - generic
    mdBottom: 4755.909
    mdTop: 4595.508
    wellbore: NO 25/11-G-12 AY2
