- wellbore:
   name: NO 25/11-G-8 BY1
   rms_name: 25_11-G-8_BY1
   short_name: G-8BY1
   slot_name: NO 25/11-G-8
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2015-07-26T00:00:00
   fluids: oil
