- wellbore:
   name: NO 25/11-G-22
   rms_name: 25_11-G-22
   short_name: G-22
   slot_name: NO 25/11-G-22
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2002-09-17T00:00:00
   fluids: oil
- interval:
    equipment: Screen
    mdBottom: 2152.72
    mdTop: 2129.38
    wellbore: NO 25/11-G-22
- interval:
    equipment: Screen
    mdBottom: 2282.78
    mdTop: 2164.47
    wellbore: NO 25/11-G-22
- interval:
    equipment: Screen
    mdBottom: 2436.99
    mdTop: 2294.78
    wellbore: NO 25/11-G-22
- interval:
    equipment: Screen
    mdBottom: 2518.26
    mdTop: 2448.0
    wellbore: NO 25/11-G-22
- interval:
    equipment: Screen
    mdBottom: 2649.14
    mdTop: 2530.26
    wellbore: NO 25/11-G-22
- interval:
    equipment: Screen
    mdBottom: 2697.05
    mdTop: 2650.16
    wellbore: NO 25/11-G-22
- interval:
    equipment: Screen
    mdBottom: 2814.93
    mdTop: 2708.63
    wellbore: NO 25/11-G-22
- interval:
    equipment: Screen
    mdBottom: 2884.98
    mdTop: 2815.93
    wellbore: NO 25/11-G-22
