- wellbore:
   name: NO 25/11-G-24 A
   rms_name: 25_11-G-24_A
   short_name: G-24A
   slot_name: NO 25/11-G-24
   field: Grane
   type: injection
   rkb: 69.9
   drilling_end_date: 2001-11-12T00:00:00
   fluids: gas
- interval:
    equipment: Screen
    mdBottom: 2981.18
    mdTop: 2296.36
    wellbore: NO 25/11-G-24 A
