- wellbore:
   name: NO 25/11-G-12 Y1
   rms_name: 25_11-G-12_Y1
   short_name: G-12Y1
   slot_name: NO 25/11-G-12
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2006-10-21T00:00:00
   fluids: oil
