- wellbore:
   name: NO 25/11-G-7 CY2
   rms_name: 25_11-G-7_CY2
   short_name: G-7CY2
   slot_name: NO 25/11-G-7
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2019-12-26T00:00:00
   fluids: oil
- interval:
    equipment: Screen
    mdBottom: 4515.042
    mdTop: 4503.324
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 4538.67
    mdTop: 4527.036
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 4562.686
    mdTop: 4550.661
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 4585.88
    mdTop: 4574.683
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 4609.659
    mdTop: 4597.879
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 4632.893
    mdTop: 4621.658
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 4656.784
    mdTop: 4644.913
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 4680.546
    mdTop: 4668.783
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 4704.44
    mdTop: 4692.535
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 4728.089
    mdTop: 4716.434
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 4751.953
    mdTop: 4740.088
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 4775.745
    mdTop: 4763.972
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 4799.466
    mdTop: 4787.745
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 4823.259
    mdTop: 4811.47
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 4846.88
    mdTop: 4835.253
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 4870.648
    mdTop: 4858.879
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 4893.862
    mdTop: 4882.648
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 4917.632
    mdTop: 4905.862
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 4940.859
    mdTop: 4929.143
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 4964.768
    mdTop: 4952.863
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 4988.493
    mdTop: 4976.778
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5011.788
    mdTop: 5000.02
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5035.561
    mdTop: 5023.779
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 5059.331
    mdTop: 5047.565
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5083.04
    mdTop: 5071.335
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5107.047
    mdTop: 5095.045
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5131.039
    mdTop: 5119.028
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5154.863
    mdTop: 5143.04
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 5178.588
    mdTop: 5166.866
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5202.35
    mdTop: 5190.591
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5225.683
    mdTop: 5214.352
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5249.55
    mdTop: 5237.689
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5273.326
    mdTop: 5261.554
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5297.32
    mdTop: 5285.317
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5321.318
    mdTop: 5309.322
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5345.017
    mdTop: 5333.316
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5368.726
    mdTop: 5357.014
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5392.764
    mdTop: 5380.753
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5415.784
    mdTop: 5404.742
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5439.524
    mdTop: 5427.803
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 6315.943
    mdTop: 6304.325
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 6339.718
    mdTop: 6327.94
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 6363.437
    mdTop: 6351.718
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 6386.947
    mdTop: 6375.44
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5985.885
    mdTop: 5973.882
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 6009.906
    mdTop: 5997.888
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 6033.896
    mdTop: 6021.899
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 6057.599
    mdTop: 6045.899
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 6080.352
    mdTop: 6068.894
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 6104.229
    mdTop: 6092.358
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 6128.027
    mdTop: 6116.242
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 6151.292
    mdTop: 6140.032
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 6175.015
    mdTop: 6163.3
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 6198.735
    mdTop: 6187.035
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 6222.452
    mdTop: 6210.758
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 6245.477
    mdTop: 6234.456
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 6268.457
    mdTop: 6257.482
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 6292.321
    mdTop: 6280.459
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5463.404
    mdTop: 5451.529
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5487.18
    mdTop: 5475.413
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5510.904
    mdTop: 5499.179
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5534.605
    mdTop: 5522.908
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5558.602
    mdTop: 5546.597
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5582.316
    mdTop: 5570.602
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5605.618
    mdTop: 5594.306
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5629.491
    mdTop: 5617.613
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5653.256
    mdTop: 5641.492
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5676.486
    mdTop: 5665.258
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 5700.492
    mdTop: 5688.481
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5724.257
    mdTop: 5712.493
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5748.171
    mdTop: 5736.255
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5771.611
    mdTop: 5760.171
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5795.29
    mdTop: 5783.572
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5818.989
    mdTop: 5807.288
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5843.013
    mdTop: 5830.997
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5867.023
    mdTop: 5855.019
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5890.713
    mdTop: 5879.021
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5914.153
    mdTop: 5902.719
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5937.861
    mdTop: 5926.165
    wellbore: NO 25/11-G-7 CY2
- interval:
    equipment: Screen
    mdBottom: 5961.86
    mdTop: 5949.859
    wellbore: NO 25/11-G-7 CY2
