- wellbore:
   name: NO 25/11-G-11 AT6
   rms_name: 25_11-G-11_AT6
   short_name: G-11AT6
   slot_name: NO 25/11-G-11
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2013-04-01T00:00:00
   fluids: oil
