- wellbore:
   name: NO 25/11-G-6 AY1
   rms_name: 25_11-G-6_AY1
   short_name: G-6AY1
   slot_name: NO 25/11-G-6
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2016-07-31T00:00:00
   fluids: oil
