- wellbore:
   name: NO 25/11-G-2 Y2T2
   rms_name: 25_11-G-2_Y2T2
   short_name: G-2Y2T2
   slot_name: NO 25/11-G-2
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2007-10-31T00:00:00
   fluids: oil
- interval:
    equipment: Screen
    mdBottom: 4197.81
    mdTop: 4139.74
    wellbore: NO 25/11-G-2 Y2T2
- interval:
    equipment: Screen
    mdBottom: 4339.64
    mdTop: 4203.68
    wellbore: NO 25/11-G-2 Y2T2
- interval:
    equipment: Screen
    mdBottom: 4351.97
    mdTop: 4339.64
    wellbore: NO 25/11-G-2 Y2T2
- interval:
    equipment: Screen
    mdBottom: 4401.94
    mdTop: 4351.97
    wellbore: NO 25/11-G-2 Y2T2
- interval:
    equipment: Screen
    mdBottom: 4413.93
    mdTop: 4401.94
    wellbore: NO 25/11-G-2 Y2T2
- interval:
    equipment: Screen
    mdBottom: 4685.02
    mdTop: 4413.93
    wellbore: NO 25/11-G-2 Y2T2
