- wellbore:
   name: NO 25/11-G-13 A
   rms_name: 25_11-G-13_A
   short_name: G-13A
   slot_name: NO 25/11-G-13
   field: Grane
   type: observation
   rkb: 69.9
   drilling_end_date: 2009-09-04T00:00:00
   fluids: not applicable
