- wellbore:
   name: NO 25/11-G-34 AY1
   rms_name: 25_11-G-34_AY1
   short_name: G-34AY1
   slot_name: NO 25/11-G-34
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2018-12-24T00:00:00
   fluids: oil
- interval:
    equipment: Screen - generic
    mdBottom: 3130.0
    mdTop: 3115.511
    wellbore: NO 25/11-G-34 AY1
- interval:
    equipment: Screen - generic
    mdBottom: 3343.357
    mdTop: 3319.349
    wellbore: NO 25/11-G-34 AY1
- interval:
    equipment: Screen - generic
    mdBottom: 3379.172
    mdTop: 3355.176
    wellbore: NO 25/11-G-34 AY1
- interval:
    equipment: Screen - generic
    mdBottom: 3414.868
    mdTop: 3390.984
    wellbore: NO 25/11-G-34 AY1
- interval:
    equipment: Screen - generic
    mdBottom: 3522.501
    mdTop: 3426.68
    wellbore: NO 25/11-G-34 AY1
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 3534.497
    mdTop: 3522.501
    wellbore: NO 25/11-G-34 AY1
- interval:
    equipment: Screen - generic
    mdBottom: 3664.677
    mdTop: 3534.497
    wellbore: NO 25/11-G-34 AY1
