- wellbore:
   name: NO 25/11-G-1 Y3
   rms_name: 25_11-G-1_Y3
   short_name: G-1Y3
   slot_name: NO 25/11-G-1
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2008-03-30T00:00:00
   fluids: oil
