- wellbore:
   name: NO 25/11-G-5 CY1T4
   rms_name: 25_11-G-5_CY1T4
   short_name: G-5CY1T4
   slot_name: NO 25/11-G-5
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2019-03-17T00:00:00
   fluids: 
- interval:
    equipment: Screen - generic
    mdBottom: 2931.57
    mdTop: 2920.005
    wellbore: NO 25/11-G-5 CY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 2954.664
    mdTop: 2943.573
    wellbore: NO 25/11-G-5 CY1T4
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 2978.374
    mdTop: 2966.66
    wellbore: NO 25/11-G-5 CY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 3002.134
    mdTop: 2990.381
    wellbore: NO 25/11-G-5 CY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 3025.721
    mdTop: 3014.14
    wellbore: NO 25/11-G-5 CY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 3049.445
    mdTop: 3037.572
    wellbore: NO 25/11-G-5 CY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 3073.099
    mdTop: 3061.399
    wellbore: NO 25/11-G-5 CY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 3096.862
    mdTop: 3085.11
    wellbore: NO 25/11-G-5 CY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 2862.151
    mdTop: 2850.582
    wellbore: NO 25/11-G-5 CY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 2884.775
    mdTop: 2873.0
    wellbore: NO 25/11-G-5 CY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 2908.479
    mdTop: 2896.782
    wellbore: NO 25/11-G-5 CY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 3119.488
    mdTop: 3107.711
    wellbore: NO 25/11-G-5 CY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 3157.19
    mdTop: 3145.406
    wellbore: NO 25/11-G-5 CY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 3180.465
    mdTop: 3168.793
    wellbore: NO 25/11-G-5 CY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 3203.971
    mdTop: 3192.465
    wellbore: NO 25/11-G-5 CY1T4
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 3227.601
    mdTop: 3215.785
    wellbore: NO 25/11-G-5 CY1T4
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 3251.387
    mdTop: 3239.621
    wellbore: NO 25/11-G-5 CY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 3275.111
    mdTop: 3263.399
    wellbore: NO 25/11-G-5 CY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 3298.877
    mdTop: 3287.124
    wellbore: NO 25/11-G-5 CY1T4
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 3322.4
    mdTop: 3310.595
    wellbore: NO 25/11-G-5 CY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 3346.184
    mdTop: 3334.411
    wellbore: NO 25/11-G-5 CY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 3368.939
    mdTop: 3357.156
    wellbore: NO 25/11-G-5 CY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 3392.642
    mdTop: 3380.867
    wellbore: NO 25/11-G-5 CY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 3416.249
    mdTop: 3404.474
    wellbore: NO 25/11-G-5 CY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 3439.855
    mdTop: 3428.071
    wellbore: NO 25/11-G-5 CY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 3462.918
    mdTop: 3451.552
    wellbore: NO 25/11-G-5 CY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 3486.516
    mdTop: 3474.742
    wellbore: NO 25/11-G-5 CY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 3510.135
    mdTop: 3498.352
    wellbore: NO 25/11-G-5 CY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 3533.689
    mdTop: 3521.972
    wellbore: NO 25/11-G-5 CY1T4
- interval:
    equipment: Screen - generic
    mdBottom: 3557.308
    mdTop: 3545.529
    wellbore: NO 25/11-G-5 CY1T4
