- wellbore:
   name: NO 25/11-G-17 CY1
   rms_name: 25_11-G-17_CY1
   short_name: G-17CY1
   slot_name: NO 25/11-G-17
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2012-09-30T00:00:00
   fluids: oil
