- wellbore:
   name: NO 25/11-G-7 AY1
   rms_name: 25_11-G-7_AY1
   short_name: G-7AY1
   slot_name: NO 25/11-G-7
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2010-09-13T00:00:00
   fluids: oil
