- wellbore:
   name: NO 25/11-G-39 AY1
   rms_name: 25_11-G-39_AY1
   short_name: G-39AY1
   slot_name: NO 25/11-G-39
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2006-07-22T00:00:00
   fluids: not applicable
