- wellbore:
   name: NO 25/11-G-5 BY4T2
   rms_name: 25_11-G-5_BY4T2
   short_name: G-5BY4T2
   slot_name: NO 25/11-G-5
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2011-12-29T00:00:00
   fluids: oil
