- wellbore:
   name: NO 25/11-G-19 AT3
   rms_name: 25_11-G-19_AT3
   short_name: G-19AT3
   slot_name: NO 25/11-G-19
   field: Grane
   type: observation
   rkb: 69.9
   drilling_end_date: 2014-07-16T00:00:00
   fluids: oil
