- wellbore:
   name: NO 25/11-G-8 AT2
   rms_name: 25_11-G-8_AT2
   short_name: G-8AT2
   slot_name: NO 25/11-G-8
   field: Grane
   type: observation
   rkb: 69.9
   drilling_end_date: 2015-07-20T00:00:00
   fluids: oil
