- wellbore:
   name: NO 25/11-G-19 EY1T2
   rms_name: 25_11-G-19_EY1T2
   short_name: G-19EY1T2
   slot_name: NO 25/11-G-19
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2014-08-18T00:00:00
   fluids: oil
- interval:
    equipment: Screen - generic
    mdBottom: 2893.75
    mdTop: 2844.975
    wellbore: NO 25/11-G-19 EY1T2
- interval:
    equipment: Screen - generic
    mdBottom: 3029.494
    mdTop: 2893.75
    wellbore: NO 25/11-G-19 EY1T2
