- wellbore:
   name: NO 25/11-G-27
   rms_name: 25_11-G-27
   short_name: G-27
   slot_name: NO 25/11-G-27
   field: Grane
   type: observation
   rkb: 69.9
   drilling_end_date: 2002-01-23T00:00:00
   fluids: not applicable
