- wellbore:
   name: NO 25/11-G-16 Y2
   rms_name: 25_11-G-16_Y2
   short_name: G-16Y2
   slot_name: NO 25/11-G-16
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2008-10-02T00:00:00
   fluids: oil
