- wellbore:
   name: NO 25/11-G-29 Y3
   rms_name: 25_11-G-29_Y3
   short_name: G-29Y3
   slot_name: NO 25/11-G-29
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2017-05-28T00:00:00
   fluids: oil
- interval:
    equipment: Screen - generic
    mdBottom: 2617.65
    mdTop: 2447.414
    wellbore: NO 25/11-G-29 Y3
- interval:
    equipment: Screen - generic
    mdBottom: 2629.69
    mdTop: 2617.65
    wellbore: NO 25/11-G-29 Y3
- interval:
    equipment: Screen - generic
    mdBottom: 2642.206
    mdTop: 2629.69
    wellbore: NO 25/11-G-29 Y3
- interval:
    equipment: Screen - generic
    mdBottom: 2654.722
    mdTop: 2642.206
    wellbore: NO 25/11-G-29 Y3
- interval:
    equipment: Screen - generic
    mdBottom: 2674.663
    mdTop: 2662.147
    wellbore: NO 25/11-G-29 Y3
- interval:
    equipment: Screen - generic
    mdBottom: 2903.272
    mdTop: 2687.182
    wellbore: NO 25/11-G-29 Y3
- interval:
    equipment: Screen - generic
    mdBottom: 3345.483
    mdTop: 2915.272
    wellbore: NO 25/11-G-29 Y3
