- wellbore:
   name: NO 25/11-G-23 A
   rms_name: 25_11-G-23_A
   short_name: G-23A
   slot_name: NO 25/11-G-23
   field: Grane
   type: injection
   rkb: 69.9
   drilling_end_date: 2011-07-07T00:00:00
   fluids: water
