- wellbore:
   name: NO 25/11-G-34 AY3T2
   rms_name: 25_11-G-34_AY3T2
   short_name: G-34AY3T2
   slot_name: NO 25/11-G-34
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2019-01-05T00:00:00
   fluids: 
