- wellbore:
   name: NO 25/11-G-13 Y1T2
   rms_name: 25_11-G-13_Y1T2
   short_name: G-13Y1T2
   slot_name: NO 25/11-G-13
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2009-05-16T00:00:00
   fluids: oil
