- wellbore:
   name: NO 25/11-G-36
   rms_name: 25_11-G-36
   short_name: G-36
   slot_name: NO 25/11-G-36
   field: Grane
   type: injection
   rkb: 69.9
   drilling_end_date: 2012-07-16T00:00:00
   fluids: water
- interval:
    equipment: Screen - generic
    mdBottom: 1962.84
    mdTop: 1422.83
    wellbore: NO 25/11-G-36
