- wellbore:
   name: NO 25/11-G-38 AY3
   rms_name: 25_11-G-38_AY3
   short_name: G-38AY3
   slot_name: NO 25/11-G-38
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2011-05-19T00:00:00
   fluids: oil
- interval:
    equipment: Screen & Blank Pipe - generic
    mdBottom: 4432.848
    mdTop: 4346.222
    wellbore: NO 25/11-G-38 AY3
- interval:
    equipment: Screen
    mdBottom: 4494.801
    mdTop: 4445.188
    wellbore: NO 25/11-G-38 AY3
- interval:
    equipment: Screen
    mdBottom: 4515.717
    mdTop: 4503.531
    wellbore: NO 25/11-G-38 AY3
- interval:
    equipment: Screen
    mdBottom: 5068.545
    mdTop: 4615.509
    wellbore: NO 25/11-G-38 AY3
- interval:
    equipment: Screen & Blank Pipe - generic
    mdBottom: 5155.04
    mdTop: 5068.545
    wellbore: NO 25/11-G-38 AY3
- interval:
    equipment: Screen
    mdBottom: 5864.378
    mdTop: 5155.04
    wellbore: NO 25/11-G-38 AY3
- interval:
    equipment: Screen & Blank Pipe - generic
    mdBottom: 5950.27
    mdTop: 5864.378
    wellbore: NO 25/11-G-38 AY3
- interval:
    equipment: Screen
    mdBottom: 6246.314
    mdTop: 5950.27
    wellbore: NO 25/11-G-38 AY3
- interval:
    equipment: Screen & Blank Pipe - generic
    mdBottom: 6392.943
    mdTop: 6258.013
    wellbore: NO 25/11-G-38 AY3
- interval:
    equipment: Screen
    mdBottom: 6577.937
    mdTop: 6405.457
    wellbore: NO 25/11-G-38 AY3
- interval:
    equipment: Screen
    mdBottom: 7055.756
    mdTop: 6762.128
    wellbore: NO 25/11-G-38 AY3
