- wellbore:
   name: NO 25/11-G-30 Y2
   rms_name: 25_11-G-30_Y2
   short_name: G-30Y2
   slot_name: NO 25/11-G-30
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2007-01-31T00:00:00
   fluids: oil
- interval:
    equipment: Screen
    mdBottom: 2807.837
    mdTop: 2782.82
    wellbore: NO 25/11-G-30 Y2
- interval:
    equipment: Screen
    mdBottom: 2845.214
    mdTop: 2820.264
    wellbore: NO 25/11-G-30 Y2
- interval:
    equipment: Screen
    mdBottom: 2882.367
    mdTop: 2857.595
    wellbore: NO 25/11-G-30 Y2
- interval:
    equipment: Screen
    mdBottom: 2981.362
    mdTop: 2894.804
    wellbore: NO 25/11-G-30 Y2
- interval:
    equipment: Screen - generic
    mdBottom: 3876.377
    mdTop: 2981.362
    wellbore: NO 25/11-G-30 Y2
