- wellbore:
   name: NO 25/11-G-38 AY2T3
   rms_name: 25_11-G-38_AY2T3
   short_name: G-38AY2T3
   slot_name: NO 25/11-G-38
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2011-05-11T00:00:00
   fluids: oil
- interval:
    equipment: Screen
    mdBottom: 6052.744
    mdTop: 4708.682
    wellbore: NO 25/11-G-38 AY2T3
- interval:
    equipment: Screen
    mdBottom: 6643.48
    mdTop: 6298.217
    wellbore: NO 25/11-G-38 AY2T3
- interval:
    equipment: Screen
    mdBottom: 4672.008
    mdTop: 4537.711
    wellbore: NO 25/11-G-38 AY2T3
