- wellbore:
   name: NO 25/11-G-10 Y2
   rms_name: 25_11-G-10_Y2
   short_name: G-10Y2
   slot_name: NO 25/11-G-10
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2006-01-27T00:00:00
   fluids: oil
- interval:
    equipment: Screen - generic
    mdBottom: 2944.206
    mdTop: 2523.829
    wellbore: NO 25/11-G-10 Y2
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 2955.911
    mdTop: 2944.206
    wellbore: NO 25/11-G-10 Y2
- interval:
    equipment: Screen - generic
    mdBottom: 3002.706
    mdTop: 2955.911
    wellbore: NO 25/11-G-10 Y2
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 3014.415
    mdTop: 3002.706
    wellbore: NO 25/11-G-10 Y2
- interval:
    equipment: Screen - generic
    mdBottom: 3084.335
    mdTop: 3014.415
    wellbore: NO 25/11-G-10 Y2
- interval:
    equipment: Screen
    mdBottom: 3388.084
    mdTop: 3084.335
    wellbore: NO 25/11-G-10 Y2
- interval:
    equipment: Screen - generic
    mdBottom: 3443.813
    mdTop: 3408.736
    wellbore: NO 25/11-G-10 Y2
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 3455.506
    mdTop: 3443.813
    wellbore: NO 25/11-G-10 Y2
- interval:
    equipment: Screen - generic
    mdBottom: 3664.729
    mdTop: 3455.506
    wellbore: NO 25/11-G-10 Y2
- interval:
    equipment: Screen - generic
    mdBottom: 3699.746
    mdTop: 3664.729
    wellbore: NO 25/11-G-10 Y2
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 3711.431
    mdTop: 3699.746
    wellbore: NO 25/11-G-10 Y2
- interval:
    equipment: Screen - generic
    mdBottom: 3793.176
    mdTop: 3711.431
    wellbore: NO 25/11-G-10 Y2
- interval:
    equipment: Screen - generic
    mdBottom: 3848.653
    mdTop: 3813.713
    wellbore: NO 25/11-G-10 Y2
- interval:
    equipment: Screen w. Swell Packer - generic
    mdBottom: 3860.327
    mdTop: 3848.653
    wellbore: NO 25/11-G-10 Y2
- interval:
    equipment: Screen - generic
    mdBottom: 4256.319
    mdTop: 3860.327
    wellbore: NO 25/11-G-10 Y2
