- wellbore:
   name: NO 25/11-G-39 CY2
   rms_name: 25_11-G-39_CY2
   short_name: G-39CY2
   slot_name: NO 25/11-G-39
   field: Grane
   type: production
   rkb: 69.9
   drilling_end_date: 2018-02-24T00:00:00
   fluids: oil
- interval:
    equipment: Screen - generic
    mdBottom: 4892.335
    mdTop: 4365.857
    wellbore: NO 25/11-G-39 CY2
- interval:
    equipment: Screen - generic
    mdBottom: 4904.347
    mdTop: 4892.335
    wellbore: NO 25/11-G-39 CY2
- interval:
    equipment: Screen - generic
    mdBottom: 4963.932
    mdTop: 4904.347
    wellbore: NO 25/11-G-39 CY2
- interval:
    equipment: Screen - generic
    mdBottom: 5155.999
    mdTop: 4963.932
    wellbore: NO 25/11-G-39 CY2
- interval:
    equipment: Screen - generic
    mdBottom: 5180.012
    mdTop: 5168.0
    wellbore: NO 25/11-G-39 CY2
- interval:
    equipment: Screen - generic
    mdBottom: 5239.615
    mdTop: 5180.012
    wellbore: NO 25/11-G-39 CY2
- interval:
    equipment: Screen - generic
    mdBottom: 5251.619
    mdTop: 5239.615
    wellbore: NO 25/11-G-39 CY2
- interval:
    equipment: Screen - generic
    mdBottom: 5574.619
    mdTop: 5251.619
    wellbore: NO 25/11-G-39 CY2
- interval:
    equipment: Screen - generic
    mdBottom: 6845.338
    mdTop: 5586.62
    wellbore: NO 25/11-G-39 CY2
