- wellbore:
   list_name: AMAP
   name: PR73Y1
   rms_name: PR73Y1
   short_name: PR73Y1
   field: grane
   type: planned
   rkb: 0.0
   drilling_end_date: 
   fluids: 
   pick_name: toplowerheimdal--depthsurface.gri
   pick_md: 3220.8064561702745
