- wellbore:
   list_name: AMAP
   name: PR78Y4
   rms_name: PR78Y4
   short_name: PR78Y4
   field: grane
   type: planned
   rkb: 0.0
   drilling_end_date: 
   fluids: 
   pick_name: toplowerheimdal--depthsurface.gri
   pick_md: 2836.45741583709
