- wellbore:
   list_name: AMAP
   name: PR82Y1
   rms_name: PR82Y1
   short_name: PR82Y1
   field: grane
   type: planned
   rkb: 0.0
   drilling_end_date: 
   fluids: 
   pick_name: toplowerheimdal--depthsurface.gri
   pick_md: 1853.0633498783966
