- wellbore:
   list_name: AMAP
   name: PR83Y1
   rms_name: PR83Y1
   short_name: PR83Y1
   field: grane
   type: planned
   rkb: 0.0
   drilling_end_date: 
   fluids: 
   pick_name: toplowerheimdal--depthsurface.gri
   pick_md: 2035.009175804688
