- wellbore:
   list_name: AMAP
   name: PR80Y2
   rms_name: PR80Y2
   short_name: PR80Y2
   field: grane
   type: planned
   rkb: 0.0
   drilling_end_date: 
   fluids: 
   pick_name: toplowerheimdal--depthsurface.gri
   pick_md: 1923.615863417721
