- wellbore:
   list_name: AMAP
   name: PR85Y2
   rms_name: PR85Y2
   short_name: PR85Y2
   field: grane
   type: planned
   rkb: 0.0
   drilling_end_date: 
   fluids: 
   pick_name: toplowerheimdal--depthsurface.gri
   pick_md: 2115.378111164277
