- wellbore:
   list_name: AMAP
   name: PR91Y1
   rms_name: PR91Y1
   short_name: PR91Y1
   field: grane
   type: planned
   rkb: 0.0
   drilling_end_date: 
   fluids: 
   pick_name: toplowerheimdal--depthsurface.gri
   pick_md: 4202.942523861275
