- wellbore:
   list_name: AMAP
   name: PR90Y1
   rms_name: PR90Y1
   short_name: PR90Y1
   field: grane
   type: planned
   rkb: 0.0
   drilling_end_date: 
   fluids: 
   pick_name: toplowerheimdal--depthsurface.gri
   pick_md: 2979.3242392415964
